### ISSUE TITLE
Is it possible to override default @context in ORION-LD?

### ISSUE THREAD

**Issue by gpedras** [Fiware/context.Orion-LD#1038]
Hi,

I'm using ORION-LD in my project to receive data observations. My issue is: for instance, let's say I want to POST "AirQualityObserved" data. Whenever I POST this data with the @context "https://smartdatamodels.org/context.jsonld" inside the Body, when I do a simple GET request the @context is overriden by "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld", and the data keynames inside the JSONLD are URLs. To bypass this issue, in the GET request I need to provide the "Link" header with the right context.

So, is there a way to override the default context when POSTing the data? And what's the point of having the @context in the body when it's just going to be replaced by the default context?

**Comment by kzangeli** [comment]
Hi,

no, you can't override the Core Context - it's ... "holy".
An NGSI-LD broker cannot function correctly if the Core Context is modified.

BUT, if you avoid to use the terms from the core context (and AirQualityObserved is not part of  the core context), your user context (either given in the Link HTTP header or as an @context field in the payload body + Content-Type: application/ld+json), then the core context will not "disturb" you.

Your user context is never "replaced" by the core context.
It's just that the core context overrides any term defined in both your user context and the core context.
The core context always "wins".
Just avoid to use terms from the core context.

And, to have your user context used for a GET operation, then, yes, you have to supply it in the Link header.
