### ISSUE TITLE
LanguageProperty Support?

### ISSUE THREAD

**Issue by dpatil-fw** [Fiware/context.Orion-LD#1040]
Around when are we planning to add support for LanguageProperty? Wanted to use this feature for multilingual support.

My POST request with LanguageProperty is giving error:
{"type":"https://uri.etsi.org/ngsi-ld/errors/BadRequestData","title":"Invalid type for attribute","detail":"LanguageProperty"}

I didn't see LanguageProperty handled here: src\lib\orionld\kjTree\kjTreeToContextAttribute.cpp

**Comment by kzangeli** [comment]
Yeah, I haven't implemented this feature yet.
I have a few urgent and pretty big things to do but, Lang-Props is also high up in my ToDo.
Pretty sure it will be implemented this year.
I can't really say much more right now, sorry ...

**Comment by kzangeli** [comment]
Actually, it seems now it will be implemented inside of 2-3 months

**Comment by dpatil-fw** [comment]
Okay, thank you.

**Comment by kzangeli** [comment]
I forgot, sorry.
LanguageProperty is supported by Orion-LD since ... about a month.
Please try it out and let me know.
It's supported for notifications as well (you can set a "lang" as part of a subscription).

**Comment by dpatil-fw** [comment]
I am sorry to get back late. I was tied up with some other work. I tested it today, with the latest orion-ld docker build and still see the same error.

Does this condition with 'experimental' in(src\lib\orionld\kjTree\kjTreeToContextAttribute.cpp) code need to be removed?

` else if (strcmp(nodeP->value.s, "LanguageProperty") == 0)
      {
        if (experimental == true)
        {
          isProperty         = true;
          isLanguageProperty = true;
        }
        else
        {
          orionldError(OrionldBadRequestData, "Invalid Attribute Type", "LanguageProperty", 501);
          return false;
        }
      }`

**Comment by kzangeli** [comment]
Ah, sorry, I forgot.
You need to start the broker with the CLI option `-experimental` (as you have already kind of seen in the source code)

**Comment by dpatil-fw** [comment]
It works with -experimental option. Thank you.

**Comment by kzangeli** [comment]
Happy to hear it !
Start testing then! :)
As soon as we feel comfortable with this new feature, I'll remove the "if -experimental" condition.
Know that you can also get notifications with LanguageProperties, and if you want those properties "converted into a specific language", just set the "lang" field (it's new) to e.g. "en" in the subscription - same is implemented for query, but as a URI parameter called ĺang':  `GET /entities?type=X&lang=es` - to get lang-properties in Spanish. See the API spec for complete info.

[ When `lang' is used, the LanguageProperty is presented as a Property, with the value of that specific language, as found inside the languageMap.]

**Comment by dpatil-fw** [comment]
Thank you for the explanation, I will look through the API spec for more details.
 
I did some more testing and I found an issue. While simple strings work fine with LanguageProperty, I have issues when I send a list of strings. I get this error:

{"type":"https://uri.etsi.org/ngsi-ld/errors/BadRequestData","title":"Items of the value of a LanguageProperty attribute must be JSON Strings","detail":"https://uri.fiware.org/ns/data-models#options"}

I have a quiz app and need to provide the user with 4 options, here is a sample payload that I am using:

{
	"@context": "http://X.X.X.X/static/ngsi-context.jsonld",
	"id": "urn:ngsi-ld:Question:750002", "type": "Question",
	"location": {
		"type": "GeoProperty",
		"value": {
			"type": "Point",
			"coordinates": [2.3499, 48.8530]
		}
	},
	"options": {
		"type": "LanguageProperty",
		"languageMap": {
			"en": ["Amiens Cathedral", "Saint Lazare Cathedral", "Saint Pierre Cathedral", "Notre Dame Cathedral"],
			"hi": ["अमीएन्स कैथेड्रल", "सेंट लज़ारे कैथेड्रल", "सेंट पियरे कैथेड्रल", "नोट्रे डेम कैथेड्रल"]
		}
	},
	"description": {
		"type": "LanguageProperty",
		"languageMap": {
			"en": "Notre-Dame is a medieval Catholic cathedral.",
			"hi": "नोट्रे-डेम एक मध्ययुगीन कैथोलिक कैथेड्रल है।"
		}
	}
}

Please let me know if such a use case will be supported - where LanguageProperty attribute could be a list of strings?

**Comment by kzangeli** [comment]
Sorry, that's not how we've specified the LanguageProperty attribute.
We only allow you to have string as "values after the language", e,g, `"es": "word in Spanish"`.
Well, right now anyway.
If you make a compelling case, the ETSI ISG CIM is a flexible group, always looking for the best of the NGSI-LD API.

Anyway, what you want to do (the options array) could be done using normal properties. You¡d have top do the "language logic" yourself, of course.

Meanwhile, I'll add this "array of strings as RHS" for languageMap as a discussion point in ETSI ISG CIM.
[ I might need some help from you to make the case, convincing people that this is actually a good idea. ]

**Comment by dpatil-fw** [comment]
On further investigation, I see even OpenStreetMaps do not support multiple values natively in their schema yet. 
[https://wiki.openstreetmap.org/wiki/Multiple_values](https://wiki.openstreetmap.org/wiki/Multiple_values)

One of the suggestions they have made is to use semi-colon separator. I think that will work for me.

**Comment by kzangeli** [comment]
ok, good to know.
We will still look into it.
If possible (depends on the core context), we'll add an array of strings as possible RHS for LanguageProperty.

**Comment by kzangeli** [comment]
Just one detail:
If you go for using a single string (personally I'd use a Property an array per language) - pick a stronger delimiter than just ';'.
Perhaps a triple: ";;;". Well, something "more strange" than just a semicolon - you might want to use a semicolon in your phrases.
If the semicolon is a delimiter, you can't.

**Comment by dpatil-fw** [comment]
Yes, I will keep that in mind. Thank you for the suggestion.

**Comment by kzangeli** [comment]
So, in the last ETSI ISG CIM I brought up the array of strings as RHS for languageMap langs:
```
  "langprop": {
    "type": "LanguageProperty",
    "languageMap": {
      "en": [ "Option One", "Option Two", ... ],
      "es": [ "Opción Uno", "Opción Dos", ... ]
  }
```
and it seems like we'll add support for it.
Looking at it briefly, we haven't found anything that argues against it, so, we're all OK with supporting it.
Either a string, or an array of strings.

If all goes well, and as soon as it enters the draft of the spec, I'll implement it in Orion-LD.
Not anytime soon though. Possibly some time in 2022, but, no promises.

**Comment by dpatil-fw** [comment]
Good to know. Thank you.

**Comment by kzangeli** [comment]
Completely forgot to inform you ...
The array for languageMaps was accepted by ETSI ISG CIM and I implemented it in Orion-LD, quite some time ago.

**Comment by dpatil-fw** [comment]
Thank you very much for implementing this.
I'll close this
