### ISSUE TITLE
Attribute does not exist

### ISSUE THREAD

**Issue by ciesse79** [Fiware/context.Orion-LD#108]
From NGSI-LD Test:
1. created entity successfully
{
      'id': 'urn:ngsi-ld:T:001',
      'type': 'T',
      'P1': {
        'type': 'Property',
        'value': 'Hola'
      }
    }
2. update fails with: 
 {
      'P1': {
        'type': 'Property',
        'value': 'Ciao'
      }
    }

Orion-LD returns:
 {type: 'http://uri.etsi.org/ngsi-ld/errors/BadRequestData',
     title: 'Attribute does not exist',
     details: 'P1' }
}
Used docker version. Endpoint : http://loalhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:T:001
HTTP Method: PATCH
Header: Content-type: application/json

There is something wrong?
Thank you.
Cris

**Comment by kzangeli** [comment]
That's a very basic operation ...
Add the details of the two requests, and I will look into it. One explanation to this would be if you used different contexts in the two requests.
Add the details of the requests and we'll see what we can do

**Comment by ciesse79** [comment]
Hi Ken,
very basic I know...
I'm using postman for both requests, and both are sent with content-type: application/json so no specific context, using the default provided by orion itself.

Create request is using POST http method. Endpoint: http://localhost:1026/ngsi-ld/v1/entities

Update request is using PATCH http method. Endpoint: http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:T:001/attrs

To give you more infos:
1. as said I used "docker-compose instructions" for my test env. 
2. with GET on http://localhost:1026/ngsi-ld/ex/v1/version it give me this result:
{
    "branch": "(HEAD",
    "kbase version": "0.2",
    "kalloc version": "0.2",
    "kjson version": "0.2"
}

To be honest, crushes on this istance is very frequent.
Regards

Cris

**Comment by kzangeli** [comment]
ok, I will look into this.
A little busy for the moment.
Meanwhile, could you please try the same two operations with curl instead of postman?
Had another guy having issues with postman ... that's why I ask this of you.

**Comment by kzangeli** [comment]
And, if it works with curl but not with postman, please send me the logfile for the postman run.
You'll find the logfile in `/tmp/orionld.log`

**Comment by kzangeli** [comment]
Forget all I've said so far.

Just made a functest with your requests and I reproduce the problem.
I read your issue too fast, thought that you had done a GET after the POST.

But no, you're using PATCH which is kind of untouched land still.

I will fix this bug as soon as I can.
Thank you for reporting!

**Comment by kzangeli** [comment]
May I propose for you to use this request instead, for now:
```
POST /ngsi-ld/v1/entities/<entity-id>/attrs
```

The PATCH isn't even implemented and it will probably take some time until I get that request fully working, between business trips and vacations coming up.
I will push this PATCH request to among the top items of my ToDo list but still ...

**Comment by ciesse79** [comment]
Yep,
I've used POST succesfully.
Moreover, just to confirm that using alternatives to postman (like cURL or programamtically) reduces drastically numbers of crashes.
Thank for your suggestions Ken.
Bye
Cris

**Comment by kzangeli** [comment]
I've implemented the PATCH as well (not 100%, but should be enough for this issue to work)

**Comment by ciesse79** [comment]
Just tried and it works.
