### ISSUE TITLE
Orion-LD crashes with this payload

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#109]
POST /ngsi-ld/v1/entities/

```
{
    "id": "urn:ngsi-ld:ParkingSpot:santander:daoiz_velarde_1_5:3",
    "type": "ParkingSpot",
    "status": {
        "type": "Property",
        "value": "free",
        "observedAt": "2018-09-21T12:00:00Z"
    },
    "category": {
        "type": "Property",
        "value": [
            "onstreet"
        ]
    },
    "refParkingSite": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:ParkingSite:santander:daoiz_velarde_1_5"
    },
    "name": {
        "type": "Property",
        "value": "A-13"
    },
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -3.80356167695194,
                43.46296641666926
            ]
        }
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
        "https://schema.lab.fiware.org/ld/context"
    ]
}
```

**Comment by kzangeli** [comment]
I made a functest but didn't get any crash. Worked just fine ...
Try the test again with an up-to-date broker?

**Comment by kzangeli** [comment]
UPDATE:
    Found a few strange things when compiling in my CentOS VM.
Stuff that could provoke a crash.
It works just fine in Ubuntu but may very well crash in CentOS.
PR on its way

**Comment by kzangeli** [comment]
The PR "on the way" has been merged: https://github.com/FIWARE/context.Orion-LD/pull/121
Fixed two errors detected by the CentOS compiler, unfortunately the compiler in Ubuntu didn't catch these two errors.
One of them could provoke a crash ...

**Comment by kzangeli** [comment]
Another PR, an older one I had "forgotten", with a functest making sure this issue is a non-issue has been merged as well. With all tests 100% OK in travis: #120
