### ISSUE TITLE
JSON-LD Link header in GET requests is reported to be in error but actually it is not

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#11]
Please check the input format at 

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextConsumption/retrieve_entity_with_ldcontext_test.js#L102

**Comment by kzangeli** [comment]
This seems to be the same as issue #9.
Well, in/out.
I assumed (from examples) that the Link HTTP Header was simply a URL string.
Now I see that was a mistake ...

**Comment by kzangeli** [comment]
Fixed in https://github.com/Fiware/context.Orion-LD/commit/8b30568691b8bb1a914cca34628fd41bfc88f250.

Now the format `Link: <URL>; rel=URL; type=XXX is supported.
However, not sure what to with *rel* and *type*.
Doing nothing right now (I even stop parsing after reaching the end of the URL).
If something needs to be done about rel and type, a new issue about this should be created.

**Comment by jmcanterafonseca** [comment]
this is not fixed

please check

```
{"body": {"details": "protocol doesn't start with 'http' nor 'https'", "title": "Link HTTP Header must be a valid URL", "type": "http://example.org/ngsi-ld/errors/BadRequestData"}, "headers": {"connection": "close", "content-length": "165", "content-type": "application/json", "date": "Tue, 20 Nov 2018 17:05:24 GMT"}, "request": {"headers": {"Accept": "application/ld+json", "Link": "<https://fiware.github.io/NGSI-LD_Tests/ldContext/testContext2.jsonld>; rel=\"http://www.w3.org/ns/json-ld#context\"; type=\"application/ld+json\""}, "method": "GET", "uri": {"auth": null, "hash": null, "host": "localhost:1030", "hostname": "localhost", "href": "http://localhost:1030/ngsi-ld/v1/entities/urn%3Angsi-ld%3AT%3A1542733523802?attrs=P1", "path": "/ngsi-ld/v1/entities/urn%3Angsi-ld%3AT%3A1542733523802?attrs=P1", "pathname": "/ngsi-ld/v1/entities/urn%3Angsi-ld%3AT%3A1542733523802", "port": "1030", "protocol": "http:", "query": "attrs=P1", "search": "?attrs=P1", "slashes": true}}, "statusCode": 400}
```

**Comment by kzangeli** [comment]
This seems to be a problem with the version of orionld.
The issue should be fixed.
All functests of orionld work with the "new" format of Link HTTP Header.
If it fails somehow, I'd need detailed info on the failure.
