### ISSUE TITLE
Broken link in readme for "OpenAPI Specification of NGSI-LD"

### ISSUE THREAD

**Issue by ghost** [Fiware/context.Orion-LD#1139]
Hello,

Unfortunately, the link to the [OpenAPI Specification of NGSI-LD](https://forge.etsi.org/swagger/ui/?url=https://forge.etsi.org/gitlab/NGSI-LD/NGSI-LD/raw/master/spec/updated/full_api.json) in the project's [readme](https://github.com/FIWARE/context.Orion-LD/blob/develop/README.md) is broken. It would be great if you could update the link.

**Comment by kzangeli** [comment]
Thanks for reporting, and, yes, we'll try to fix this stupidity asap

**Comment by kzangeli** [comment]
Fixed by PR https://github.com/FIWARE/context.Orion-LD/pull/1143
