### ISSUE TITLE
Subscription receiverInfo not persisted?

### ISSUE THREAD

**Issue by EldritchKitten** [Fiware/context.Orion-LD#1165]
I am running Orion-LD on a Kubernetes cluster using image fiware/orion-ld:1.0.1. I set up several subscriptions, using the receiverInfo field to specify a HTTP header for authorisation. This worked perfectly for many weeks until something caused Orion-LD to restart, after which _the notifications continued to be sent, but without the HTTP header specified in the receiverInfo._

Related to this, _the receiverInfo field is not present in the json obtained from the ngsi-ld/v1/subscriptions GET endpoint_, even when it has been set and Orion-LD is correctly using it when sending notifications.

**Comment by kzangeli** [comment]
ok, that sounds serious.
I will look into it asap.
Think I have all the info I need to investigate. If I need more I'll come back to you.

**Comment by kzangeli** [comment]
So, I looked at it and it works just fine.
Seems like I've already fixed this issue, just, probably after 1.0.1.
Found a line about "fixing receiverInfo and notifierInfo" in my changelog and I had that feeling of deja-vu ...

So, update to a newer version of Orion-LD and try again.

Next release (1.1) is planned for end of July, in case you prefer to use only "official releases".

Whatever you do, please don't use "latest" - that's dangerous - it changes on a daily basis.

If you decide to go with a newer version, use its specific tag, not "latest".
The fix seems to have been done in the end of March.
If I were you, I'd just take the latest (1.1.0-PRE-942) and stick with it until end of July.

[Here](https://github.com/FIWARE/context.Orion-LD/pull/1166/files) is the PR making sure receiverInfo is persisted, by adding two steps to an existing functest:
* 07. Restart broker
* 08. GET S1 and see the receiverInfo
[ Check inside mongo was already implemented in that functest ]

**Comment by EldritchKitten** [comment]
Thank you for the incredibly quick response! I wasn't sure how stable the PRE-xxx tags were, so had been holding off upgrading. I will test 1.1.0-PRE-942 and get back to you.

**Comment by kzangeli** [comment]
Well, the releases are used by lots of people so they get some "free testing" there ... 
But, Orion-LD has a massive 100% covering functest suite of +1700 functests, running an average of perhaps 10 requests each, and no PR is ever admitted without this test suite running at 0% failure rate.
So, we consider every tag more or less tested.

**Comment by EldritchKitten** [comment]
That's good to know, thanks.

I can confirm that 1.1.0-PRE-942 does not have the above issues.

Thanks again!

**Comment by kzangeli** [comment]
Great, thanks!
