### ISSUE TITLE
Issues when listing subscriptions

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#117]
A subscription is created with the following `application/ld+json` payload:

```
{"type":"Subscription","@context":"https://schema.lab.fiware.org/ld/context","entities":[{"type":"ParkingSpot"}],"watchedAttributes":["status"],"notification":{"endpoint":{"uri":"http://localhost:1880/notif-LD","accept":"application/ld+json"},"format":"normalized","attributes":["status"]}}
```

Then a GET /ngsi-ld/v1/subscriptions is issued as follows:

```
curl -X GET \
  http://localhost:1030/ngsi-ld/v1/subscriptions/ \
  -H 'Accept: application/json' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: localhost:1030' \
  -H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
  -H 'Postman-Token: 3a91b721-797b-4e7f-8f1a-e07261cfd8c8,053e36cc-29bb-443f-8627-20b8adef1179' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache'
```

```
{
        "id": "urn:ngsi-ld:Subscription:5d13537c8cae7ee10f60ea97",
        "type": "Subscription",
        "entities": [
            {
                "type": "https://uri.fiware.org/ns/datamodels/ParkingSpot"
            }
        ],
        "watchedAttributes": [
            "https://uri.fiware.org/ns/datamodels/status"
        ],
        "notification": {
            "attributes": [
                "https://uri.fiware.org/ns/datamodels/status"
            ],
            "format": "normalized",
            "endpoint": {
                "uri": "http://localhost:1880/notif-LD",
                "accept": "application/ld+json"
            }
        },
        "expires": "2038-01-19T03:14:07Z"
    }
```

* `expires` should not be there 
* ldContext Mapping should have happened

**Comment by kzangeli** [comment]
There is another issue about the same, returning  the default context instead of what was sent.
Issue: (to be looked up)

**Comment by kzangeli** [comment]
About "expires":

It's a part of the subscription, given or not at creation time.
Similar to 'creationDate' and 'modificationDate', but not exactly the same ...

Three possibilities: 
* Should we treat 'expires' like those two special dates?
* Or: invent another '?options=xxx' to see expires?
* Or: simply return it in the response as it is done now (seems the most reasonable option to me)

**Comment by jmcanterafonseca** [comment]
if the expiration date has not been provided then it has not been provided. you can keep an internal expires set to "infinite" but that does not mean that it should be rendered at all. the same with throttling.

**Comment by kzangeli** [comment]
Fixed in https://github.com/FIWARE/context.Orion-LD/pull/122
