### ISSUE TITLE
Subscriptions do not work with a query

### ISSUE THREAD

**Issue by a39172** [Fiware/context.Orion-LD#1180]
This is my subscription:
```
{
    "description": "Temperature",
    "type": "Subscription",
    "entities": [
        {
            "type": "MeasurementSensor"
        }
    ],
    "q": "refRoom == urn:ngsi-ld:Room:00",
    "watchedAttributes": [
        "temperature"
    ],
    "notification": {
        "attributes": [
            "refRoom",
            "temperature"
        ],
        "format": "keyValues",
        "endpoint": {
            "uri": "http://host.docker.internal:3000/subscriptions/temperature",
            "accept": "application/json"
        }
    },
    "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
}
```

It gives an error in the query that only disappears if I change the query to:
- `"q": "refRoom == %22urn:ngsi-ld:Room:00%22"` (encoding the double quotes)

The problem is that now the subscription is only triggered if I change the static attribute `refRoom` to `%22urn:ngsi-ld:Room:00%22` in the sensor provisioning.

**Comment by kzangeli** [comment]
ok, I have understood the problem.
I have to admit this is a pretty stupid bug, makes me feel quite ashamed.
Thank you very much for finding it for me.
Apparently I never implemented a functest that tests subscriptions with a "q" filter on an attribute that is a string.
Will do that now, and fix this embarrassment as soon as I possibly can.

**Comment by kzangeli** [comment]
Ah, I forgot to mention, you did well using and encoding the double-quotes.
There's no other way around it, as it's a value of a key in JSON.
Without quotes, the RHS would be understood as a variable (a DB field) and that is something that is on the ToDo list but not yet implemented, neither in the NGSI-LD API spec nor in the Orion-LD broker.

**Comment by kzangeli** [comment]
Hopefully fixed it - please test again (using the docker image from today) and close this issue if all is good.
