### ISSUE TITLE
Backwards compatibility with QuantumLeap 8.0.3

### ISSUE THREAD

**Issue by DasNordlicht** [Fiware/context.Orion-LD#1182]
Is it possible to set the **Fiware-Service** header in addition to the **NGSI-Teanant** header in a notification?

A custom header is apparently not provided for the Subscription Endpoint.

**Comment by kzangeli** [comment]
That should be possible, yes - take a look at the field `receiverInfo` in the API spec

[  _I read your question too fast - came up with a thing I need to fix:_

_Good question - that should give an error, especially if the tenants are different.
Don't think I've implemented that error handling yet - adding it to my list, and using this issue for it._  ]

**Comment by DasNordlicht** [comment]
> That should be possible, yes - take a look at the field `receiverInfo` in the API spec
> 
Sorry, either I'm looking in a wrong specification or I can't find the **receiverInfo** field.

**Comment by kzangeli** [comment]
ok, perhaps you have an older version of the API doc?
It's is chapter **5.2.15 Endpoint** (I think it's there since v1.3.1 of the API spec).
The most recent publish spec is v1.5.1, and 1.6.1 is on its way - should be published before September.

**Comment by kzangeli** [comment]
https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_CIM009v010501p.pdf

**Comment by DasNordlicht** [comment]
ok, it works!
Thanks for the info.
With this we can work.

```
            "receiverInfo": [{
                "key": "Fiware-Service",
                "value": "captn"
                }]
```

**Comment by kzangeli** [comment]
ok!
Happy to hear it :)
