### ISSUE TITLE
How can I use ngsi-ld for entity query sorting?

### ISSUE THREAD

**Issue by dzgrief** [Fiware/context.Orion-LD#1216]
/ngsi-ld/v1/entities

What are the sorting parameters？

**Comment by wistefan** [comment]
Hi @dzgrief ,
thats not really an Orion-LD question, but rather about the NGSI-LD API. You can find the latest version here: https://docbox.etsi.org/isg/cim/open/Latest%20release%20NGSI-LD%20API%20for%20public%20comment.pdf 
A detailed description of that endpoint is under 6.4.

**Comment by kzangeli** [comment]
Hi,

you won't find any sorting mechanism in the API spec I'm afraid.
While NGSIv2 has one, NGSI-LD has not.
Orion-LD sorts the entities based on their creation time (oldest first).
It's really the only "non-idiotic" way to do pagination.

Sorry ...

/KZ
