### ISSUE TITLE
Crash on erroneous q

### ISSUE THREAD

**Issue by kiskit** [Fiware/context.Orion-LD#1229]
Hello
In the following json posted to **/subscriptions**, there is an erroneous _q_. 
```json
{
	"id": "uri:skeutuveu1",
	"description": "Light1 sub is on",
	"type": "Subscription",
	"entities": [
		{
			"type": "Device"
		}
	],
	"watchedAttributes": [
		"isOn"
	],
	"q": "brandName==Mercedes",
	"notification": {
		"attributes": [
			"isOn",
			"dataProvider",
			"day"
		],
		"format": "keyValues",
		"endpoint": {
			"uri": "http://172.31.0.1:4107/notifications/apopo",
			"accept": "application/json"
		}
	},
	"@context": [
		"https://smartdatamodels.org/context.jsonld"
	]
}
```
It makes orion-ld 1.1.0 crash after logging the message:
_qLex: ngsi-ld query language: after non-regexp comparison operator must come a non-regexp Value: Variable_

**Comment by kzangeli** [comment]
ok, noted.
Should be an easy fix.
Thanks for reporting!

**Comment by kzangeli** [comment]
BTW, you know how to fix it, right?
Just add quotes for the string:
```
	"q": "brandName==%22Mercedes%22",
```
Pretty sure you know already.
Just in case ... Wouldn't want to have you waiting and losing valuable time on a stupidity ...

**Comment by kiskit** [comment]
Actually yes, I know because I already wasted that time, so yes, no need to worry ;)

**Comment by kzangeli** [comment]
OK! :)

So, I implemented a functest for your case, exactly as you describe it in the issue.
Didn't get any crash though ...

Could you please have a look at the PR:
https://github.com/FIWARE/context.Orion-LD/pull/1230

And let me know if I missed something in the functest

False alarm - I started the broker with the CLI `-experimental`, which makes it use an alternative implementation.
All worked just fine.   When removing the -experimental CLI I saw the crash. And the I fixed it, of course :)

**Comment by kiskit** [comment]
Great, I like it when I don't really need to do anything. Thanks for the fix.

**Comment by kzangeli** [comment]
"q" for Orion-LD is complex (not only "q"), as Orion-LD implements both NGSI-LD and NGSIv2, and both APIs have "q", only, they're different ...
