### ISSUE TITLE
Do the version from the API endpoint and the one from the docker tag agree ?

### ISSUE THREAD

**Issue by fbattello** [Fiware/context.Orion-LD#1250]
Hi,

I use the Orion-LD docker image tagged `1.2.0-PRE-1117`.
When requesting the API version endpoint from the corresponding container, I get `"orionld version": "post-v1.1.0"`

It looks like that the version returned by the API is stuck to `post-1.1.0` and doesn't mirror the exact version.

**Comment by kzangeli** [comment]
Well, one thing is the version of Orion-LD and another thing is the tag in dockerhub.
Orion-LD versions change when releases are made.
dockerhub tags change for every PR merged (and new image pushed to dockerhub).
The broker itself isn't aware of the dockerhub tags.
