### ISSUE TITLE
It should be possible to overwrite DISTRO

### ISSUE THREAD

**Issue by rschwebel** [Fiware/context.Orion-LD#1253]
When cross compiling, it should be able to overwrite the DISTRO normally determined by osDistrolsh.

I'll send a pull request in a minute.

**Comment by kzangeli** [comment]
Cross-compiling the broker?
Interesting, where are you trying to run the broker?

**Comment by rschwebel** [comment]
I'm currently mostly trying to find out more about the state of the code base and its build system. For me as an embedded guy, throwing orion-ld into a cross build environment is a good way to find out, as it is more or less a cleanroom environment that has nothing that's by accident there on normal distributions :-) So integration issues are often quickly found.

In the end, I'll probably looking at what's necessary to build proper debian packages, but no promises. I don't know if I'll find the time (depends a bit on if we'll get a related project in the future).

**Comment by kzangeli** [comment]
ok, great. A cleaning process. I'm all for that!
Count on my support
