### ISSUE TITLE
 Merge-Patch update supplying the `key-values` format and a `lang` parameter not supported.

### ISSUE THREAD

**Issue by jason-fox** [Fiware/context.Orion-LD#1261]
1. Create an Entity with a **LanguageProperty**

```console
curl -L -X POST 'http://localhost:1026/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/json' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
    "id": "urn:ngsi-ld:City:001",
    "type": "City",
    "name": {
        "type": "LanguageProperty",
        "languageMap": {
            "el": "Κωνσταντινούπολις",
            "en": "Constantinople",
            "tr": "İstanbul"
        }
    }
}'
```

Attempt to Merge-Patch update supplying the `key-values` format and a `lang` parameter:

```console
curl -L -X PATCH 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:City:001?options=keyValues&lang=en' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Content-Type: application/json' \
--data-raw '{
    "name": "not-constantinople"
}'
```

The broker returns:

```json
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "Attempt to transform a LanguageProperty into a Property",
    "detail": "https://uri.etsi.org/ngsi-ld/name"
}
```

It is expected that  Key-values Merge-Patch update of a single Language should be supported

**Comment by kzangeli** [comment]
Either that or we forbid this.
It's a quite weird request ...
What if we added more fields to the patch object?
```
PATCH  /ngsi-ld/v1/entities/urn:ngsi-ld:City:001?options=keyValues&lang=en
{
  "name": "not-constantinople",
  "location": { "type": "Point", "coordinates": [ ... ] }
}
```
What should the broker do then?

`options=keyValues` breaks the merge+patch behavior, and so does `lang=es`.
Not so sure this is a very good idea.
This needs to be discussed in ETSI ISG CIM.

_It could easily be done like this instead (without key-values and lang):_
```
{
  "name": { "languageMap": { "en": "not-constantinople" }},
  "location": { "type": "Point", "coordinates": [ ... ] }
}
```
NOT breaking the merge+patch RFC

**Comment by kzangeli** [comment]
Actually, as options=keyValues, the whole RHS should be considered the value and if the attribute already exists, the attribute type can be extracted from there.
If it doesn't exist, then it will always be added as a property (or a GeoProperty as we have a rule in place to distinguish between the two).

This is not even implemented in Orion-LD yet, I just started with it.
Step 2 in that is to support also `?lang=xx`

**Comment by jason-fox** [comment]
> `options=keyValues` breaks the merge+patch behavior, and so does `lang=es`.

1. `options=keyValues`  is always short-hand for the following:

#### Property

```
"attr": { "value": {...}},
```

#### Relationship

```
"attr": { "object": "urn...."},
```

#### LanguageProperty

```
"attr":  : { "languageMap": { }},
```

2. `lang=es`  applies to **LanguageProperties** only is always:

```
"name": { "languageMap": { "es": "..." }},
```

This is a valid merge-patch document.

**Comment by jason-fox** [comment]
Obviously, a combo like:

```
"attr":  : { "languageMap": { }},
```

with ` ?lang=xx` is a **Bad Request**, as the RHS in this case must be a string or string array.

**Comment by kzangeli** [comment]
Fixed in PR https://github.com/FIWARE/context.Orion-LD/pull/1285
