### ISSUE TITLE
Subscription Credentials

### ISSUE THREAD

**Issue by ColoDidac** [Fiware/context.Orion-LD#1275]
We are trying to add some credentials to a Subscription, at first, we tried with MQTTS, but it was not possible because it had not been implemented yet.
Now I'm trying to add some credentials to an HTTP subscription, but I can't find a good way to make it work.
There's implemented any way to add credentials to a Subscription? 
Thank you!!

**Comment by kzangeli** [comment]
Yes!
Use the "receiverInfo" field inside "Subscription::notification::endpoint".
"receiverInfo" is a key-value array of HTTP headers (in the case of HTTP binding) of header names and header values.

You can create a subscription like this:
```
POST /subscriptions
{
  "id": "urn:xxx",
   ...
  "notification": {
    "endpoint": {
      "url": "xxx",
      . . . 
      "receiverInfo": [
        {
          "key": "XXX",
          "value": "YYY"
        }
      ]
    }
  }
}
```

Any notification would then be sent with the header "XXX: YYY".

That said, any update/creation of entities that provoke a notification, if they include an HTTP header "X-Auth-Token" and/or "Authorization", then that/those HTTP headers will be included in the notification request as well.

Test it and let me know.

This [functest](https://github.com/FIWARE/context.Orion-LD/blob/develop/test/functionalTest/cases/0000_ngsild/ngsild_new_notification_with_forwarded-headers-from-receiverInfo.test) tests all of the above.

**Comment by ColoDidac** [comment]
It seems that works, Thank you!!
