### ISSUE TITLE
[Subscription] Invalid Q-Filter

### ISSUE THREAD

**Issue by fbattello** [Fiware/context.Orion-LD#1276]
Hi

Orion-LD fails when trying to create the subscription sample [Notify me on low stock](https://ngsi-ld-tutorials.readthedocs.io/en/latest/subscriptions.html) from the NGSI-LD tutorial.

With the following error message :

```json
{"type":"https://uri.etsi.org/ngsi-ld/errors/BadRequestData","title":"Invalid Q-Filter","detail":"Variable"}
```

From the original sample I've just removed the tenant and replaced the context with the default context, which at the end gives that : 
```json
{
  "description": "Notify me of low feedstock on Farm:001",
  "type": "Subscription",
  "entities": [
    {
      "type": "FillingLevelSensor"
    }
  ],
  "watchedAttributes": [
    "filling"
  ],
  "q": "filling>0.6;filling<0.8;controlledAsset==urn:ngsi-ld:Building:farm001",
  "notification": {
    "attributes": [
      "filling",
      "controlledAsset"
    ],
    "format": "keyValues",
    "endpoint": {
      "uri": "http://tutorial:3000/subscription/low-stock-farm001",
      "accept": "application/json"
    }
  },
  "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
}
```
The docker image is `fiware/orion-ld:1.2.0-PRE-1123`.
I'm quite sure I had already created this subscription with a previous Orion-LD version.

**Comment by kzangeli** [comment]
Yeah this is probably due to a bug fix from my side.
Try putting  the RHS of `controlledAsset==urn:ngsi-ld:Building:farm001`  inside double quotes:
```
controlledAsset==%22urn:ngsi-ld:Building:farm001%22    (urlencoded the double quotes
```

**Comment by fbattello** [comment]
Thanks. It works bu adding `%22`.
But not sure I've understood. I'd like to know for the future (I have some subscription payloads built in Python) : which one is LD-compatible ? Without double quotes ? With double-quotes urlencoded ? Both ?
Is it a bug ?

**Comment by kzangeli** [comment]
It was a bug, but I fixed it.
You see, Orion-LD supports both NGSI-LD and NGSIv2.
NGSIv2 also has a 'q' filter. Only ... it's different.  No quotes needed for string in RHS for NGSIv2 'q'.
While, in NGSI-LD's 'q', quotes are indeed needed.

So, that's the reason behind the bug, which I found (not too long ago) and I fixed it.
It got a bit tricky to support both (slightly differtent) 'q's at the same time.

And yes, at least the quotes should be urlencoded.

**Comment by kzangeli** [comment]
One note here.
As the 'q' is "normally" used for Query of Entities, and that 'q' comes in the URL, it needs to be URL-encoded.

For subscriptions, the 'q' is part of the payload body and instead of using url-encoding, I should have gone for escaping the quotes.

I decided to not mix things and use the same mechanism for both query and subscriptions.
Not a very good decision, in retrospective and some day I'll implement the support for escaped quotes in subscription 'q':

It will then look like this:
```
"q":"filling>0.6;filling<0.8;controlledAsset==\"urn:ngsi-ld:Building:farm001\""
```

BUT, that isn't implemented yet, so stick to urlencode for now.

**Comment by kzangeli** [comment]
If you're happy with my answer, please go ahead and close the issue

**Comment by fbattello** [comment]
Thank you for your very detailed answer.
