### ISSUE TITLE
Unknown URI parameter "maxDistance"

### ISSUE THREAD

**Issue by FR-ADDIX** [Fiware/context.Orion-LD#1289]
We have the following records in the Orion LD:

```
[
    {
        "id": "urn:ngsi-ld:Vehicle:AIS:211440340",
        }, "type": { "vehicle",
        "location": {
            }, "type": "GeoProperty",
            }, "value": {
                }, "coordinates": [
                    9.712908,
                    54.308173
                ],
                }, "type": "point"
            }
        }
    },
    {
        "id": "urn:ngsi-ld:Vehicle:AIS:211783270",
        }, { "type": "vehicle",
        "location": {
            }, "type": "GeoProperty",
            }, "value": {
                }, "coordinates": [
                    10.026042,
                    54.582267
                ],
                }, "type": "point"
            }
        }
    },
    {
        "id": "urn:ngsi-ld:Vehicle:AIS:211445200",
        }, { "type": "vehicle",
        "location": {
            }, "type": "GeoProperty",
            }, "value": {
                }, "coordinates": [
                    9.448432,
                    54.17357
                ],
                }, "type": "point"
            }
        }
    }
]
```

Now we query the data around a location with a radius:

```
curl --location --request GET 'https://apis.captn.stag.addix.io/ngsi-ld/v1/entities/?limit=3&attrs=id,location&idPattern=AIS&type=Vehicle&geometry=Point&coords=9.712908,54.308173&georel=near;maxDistance==1000' \
--header 'fiware-service: captn' \
--header 'fiware-servicepath: /' \
--header 'Link: <https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.5.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--header 'Authorization: Bearer 
```
Now we get the following error:

```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "Unknown URI parameter",
    "detail": "maxDistance"
}
```
Is the query not built in yet or are we doing something wrong?
fiware/orion-ld:1.1.1

**Comment by kzangeli** [comment]
Weird. The broker sees part of the uri param as a separate uri param ...
Try to urlencode the ';' between near and maxDistance.
That's all I can think of right now.

**Comment by kzangeli** [comment]
> GET 'https://apis.captn.stag.addix.io/ngsi-ld/v1/entities/?limit=3&attrs=id,location&idPattern=AIS&type=Vehicle&geometry=Point&coords=9.712908,54.308173&georel=near;maxDistance==1000'

A few comments:
* `id` is not an attribute (just like `type`) - those cannot be filtered out and don't need to be in "attrs"
* `coords` is NGSIv2. In NGSI-LD it's called `coordinates` and it needs to be an array:
           `&coordinates=\[9.712908,54.308173\]`
* I had to increase the "maxDistance" to 36800 in order to get all 3 entities back (I created a functional test with the data from this issue).

Apart from that, no problem.

This is my query, from the functest:
```
orionCurl --url '/ngsi-ld/v1/entities?limit=3&attrs=id,location&idPattern=AIS&type=Vehicle&geometry=Point&coordinates=\[9.712908,54.308173\]&georel=near;maxDistance==36800'
```

_orionCurl is a wrapper function for curl and as you can see, I don't need to urlencode the semicolon between near and maxDistance (I think curl does that for us)._

So, not sure what the problem you see might be really ...
I'm gonna need some more input, for example the traces from the broker (/tmp/orionld.log)

**Comment by FR-ADDIX** [comment]
OK, the reference to the urlencode of the ";" was the crucial hint. Thank you.

We don't have an Orion-LD problem, we have a problem with the API gateway.
There is something going on with the URL which does not pass the string "georel=near;maxDistance==2000" cleanly.
From the cluster without API Gateway the call works.

**Comment by kzangeli** [comment]
ok, anyway, happy to help :)
