### ISSUE TITLE
Implicit including NGSI-LD @context allows arbitrary attributes

### ISSUE THREAD

**Issue by nikosft** [Fiware/context.Orion-LD#1308]
The NGSI-LD context, which is implicitly included by orion-ld,  has the following statement in the last line

```
"@vocab": "https://uri.etsi.org/ngsi-ld/default-context/"
```
This allows arbitrary attribute names. For example, orion-ld will happily accept the following
```
curl -iX POST 'http://localhost:1026/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/ld+json' \
-d '{
    "id": "urn:ngsi-ld:nonsense",
    "type": "Nonsense",
    "nonsenseproperty": {
        "type": "Property",
        "value": "nonsense value"
    },
    "@context": {}
}'
```
Since `nonsenseproperty` is mapped to `https://uri.etsi.org/ngsi-ld/default-context/nonsense`. As a matter of fact if you request the created item, i.e.,

```
curl -L -X GET 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:nonsense' \
-H 'Accept: application/ld+json'
```

And you parse the response using json-ld playground in the "Expanded" tab you will see what I am describing here. You can see the result by [clicking here](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Furi.etsi.org%2Fngsi-ld%2Fv1%2Fngsi-ld-core-context.jsonld%22%2C%22id%22%3A%22urn%3Angsi-ld%3Anonsense%22%2C%22type%22%3A%22Nonsense%22%2C%22nonsenseproperty%22%3A%7B%22type%22%3A%22Property%22%2C%22value%22%3A%22nonsense%20value%22%7D%7D&context=%7B%7D)) 

In my opinion, this is not an expected behavior and it will result in error-prone systems. For example, in systems where misspelled attributes are happily accepted.

**Comment by kzangeli** [comment]
I'm not sure where you're going with this ...
"@vocab" is an important part of the spec, making sure ANY entity type / attribute name gets correctly expanded, even when not found in the user @context, nor in the Core @context.

If I understand this issue correctly, you're using an attribute name that is not "expandable" by the @context you're providing.
Meaning, the core context will expand it "no matter what", which is exactly what "@vocab" of the core context is for, and your attribute name still get an expansion.

An NGSI-LD broker is, by design, by API definition, agnostic to data models.

**Comment by nikosft** [comment]
>making sure ANY entity type / attribute name gets correctly expanded, even when not found in the user @context, nor in the  Core @context.

I believe this is wrong behavior. What is the purpose of allowing any attribute? If you want to achieve interoperability, applications should be confined by a specific context.

**Comment by nikosft** [comment]
In other words, if you set up a context about "buildings" you expect that if somebody tries to store a "car", this request will be rejected. But this does not happen with Orion context broker.

**Comment by kzangeli** [comment]
Yeah, well, an NGSI-LD broker is agnostic to the data model by design. It's done like this on purpose.
You might not like it, but ... this is what was decided in the very start of ETSI ISG CIM (where NGSI-LD is defined).

**Comment by nikosft** [comment]
Dear @kzangeli thanks for the clarifications. I have to fully digest ETSI CIM.
