### ISSUE TITLE
Patching an entity that doesn't exist crashes the server

### ISSUE THREAD

**Issue by sjerman** [Fiware/context.Orion-LD#1346]
If you try and patch an entity that doesn't exist, the broker terminates ..

```
curl -kX PATCH -${CONTEXT_BROKER}'/entities/urn:ngsi-ld:Switch:3' \
 -H 'Link: <'${MODEL_CONTEXT}'>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
 -H 'Content-Type: application/json' \
--data-raw '{ "state": "${VALUE}" }'
```

**Comment by kzangeli** [comment]
Really?
If that is true, that's a disaster!
I'll check it right away.
Thanks for reporting!
I'm surprised I don't have a func test covering this, I normally do ...

**Comment by kzangeli** [comment]
So, I wrote a simple functest doing this:
```
payload='{
  "P1": 1
}'
orionCurl --url /ngsi-ld/v1/entities/urn:E1 -X PATCH --payload "$payload" -H 'Link: <https://fiware.github.io/data-models/context.jsonld>; rel="http://\
www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```

[ orionCurl is a wrapper for curl, I believe it's quite clear how it works just by looking at it.]


The answer I get from the broker is this:
```
HTTP/1.1 404 Not Found
Content-Length: 113
Content-Type: application/json
Date: Fri, 07 Apr 2023 08:31:13 GMT

{
    "detail": "urn:E1",
    "title": "Entity does not exist",
    "type": "https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound"
}
```

which is exactly what I would expect.

So, please give me more details (all details you can think of) on the crash you see, and we'll see if I can reproduce it.

**Comment by sjerman** [comment]
Hum. OK, this command crashes it...

 curl -kiX PATCH
http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:BinarySensor:001 \
   -H 'Content-Type: application/ld+json' \
    --data-raw '{ "state": false,  ***@***.***": "
https://registry.kloudspot.com/repository/files/fiware/datamodels.context-ngsi.jsonld
"}'

You should be able to run the command directly... the context url should be
valid. Now there may be something wrong with my context :)

Steve

**Comment by sjerman** [comment]
Running this docker image in docker desktop: fiware/orion-ld:1.2.0-PRE-1305

**Comment by kzangeli** [comment]
Ok, perfect. I'll try that. See if we're lucky ...

**Comment by kzangeli** [comment]
So, I tried this (had to add a double quote for the **@** thingy):
```
curl -kiX PATCH http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:BinarySensor:001 \
  -H 'Content-Type: application/ld+json' \
  --data-raw '{ "state": false,  "***@***.***": "https://registry.kloudspot.com/repository/files/fiware/datamodels.context-ngsi.jsonld" }'
```

And I get this error from the broker:
```
HTTP/1.1 400 Bad Request
Date: Fri, 07 Apr 2023 13:12:29 GMT
Content-Type: application/json
Content-Length: 189

{
  "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
  "title": "@context missing in JSON payload",
  "detail": "For application/ld+json, the @context must be present in the JSON payload"
}
```
Which makes a lot of sense as there's no @context in the body but 'ld+json' is used for Content-Type.

I looked at https://registry.kloudspot.com/repository/files/fiware/datamodels.context-ngsi.jsonld and that is an @context, so I change the curl to:
```
curl -kiX PATCH http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:BinarySensor:001 \
  -H 'Content-Type: application/ld+json' \
  --data-raw '{ "state": false,  "@context": "https://registry.kloudspot.com/repository/files/fiware/datamodels.context-ngsi.jsonld" }'
```
That gives me a "404 Not Found" but still no crash.

Third test, I keep as 1st but I change 'application/ld+json' for 'application/json' and I just get a 404 again.

So, still no luck.

I'll try to put the broker in docker (I'm compiling it and running it natively) - not very well versed in docker, unfortunately

**Comment by kzangeli** [comment]
No luck with docker, not my cup of tea ...
Perhaps you can help.
The broker starts, inside its docker container, but, it's unable to connect to mongo (which runs locally in my PC):
```
docker run --rm -d --name orion-ld -p 1026:1026 -e MEMORY_ENABLED=true -e LOGGERS_LEVELS_ROOT=TRACE fiware/orion-ld:1.2.0-PRE-1305
```

I have no one to ask as all my colleagues are out on easter vacation ...

**Comment by sjerman** [comment]
Hum - I’m on holiday as well :) - I’ll try a few more things when I get
back.

Thanks
Steve

**Comment by sjerman** [comment]
OK. I can't reproduce except on one system and can't figure out what makes it crash. Probably something environmental.
