### ISSUE TITLE
Subscription patch error

### ISSUE THREAD

**Issue by thinkingmik** [Fiware/context.Orion-LD#1368]
Hi,

It seems there are some problems during the subscription update through the API endpoint: `PATCH /ngsi-ld/v1/subscriptions/urn:ngsi-ld:Subscription:328a824c-ed9c-11ed-9bf8-0242ac190007`.

I'm using the Orion-LD image version `fiware/orion-ld:1.2.0-PRE-1302-debug`.

I create two subscriptions, for example:
```json
{
    "description": "Notify",
    "type": "Subscription",
    "entities": [
        {
            "type": "Humidity"
        }
    ],
    "watchedAttributes": [
        "humidity"
    ],
    "notification": {
        "attributes": [
            "humidity"
        ],
        "format": "normalized",
        "endpoint": {
            "uri": "http://quantumleap:3629/v2/notify",
            "accept": "application/json"
        }
    }
}
```
and
```json
{
    "description": "Notify",
    "type": "Subscription",
    "entities": [
        {
            "type": "Temperature"
        }
    ],
    "watchedAttributes": [
        "temperature"
    ],
    "notification": {
        "attributes": [
            "temperature"
        ],
        "format": "normalized",
        "endpoint": {
            "uri": "http://quantumleap:3629/v2/notify",
            "accept": "application/json"
        }
    }
}
```

If I try to update the **second** subscription I've got this error:
```json
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "Database Error",
    "detail": "patching a subscription"
}
```

In the Orion-LD logs i found:
```
2023-05-08 14:41:25 time=Monday 08 May 12:41:25 2023.117Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongocSubscriptionReplace.cpp[68]:mongocSubscriptionReplace | msg=mongoc error replacing subscription 'urn:ngsi-ld:Subscription:328a824c-ed9c-11ed-9bf8-0242ac190007': [17.66]: After applying the update, the (immutable) field '_id' was found to have been altered to _id: "urn:ngsi-ld:Subscription:328a824c-ed9c-11ed-9bf8-0242ac190007"
```

The update of the first subscription works fine.

**Comment by kzangeli** [comment]
ok, that is very interesting!
I'll be right on this.  Definitely looks like a bug.
Thank you for reporting!

**Comment by kzangeli** [comment]
Found the bug, fixed it. Running the test suite now to make sure I didn't break anything else.
If all goes well, there should be an updated image on dockerhub/quay before lunch tomorrow.
(Or, if against all odds, my son falls asleep early, it'll be ready some time before midnight)

**Comment by kzangeli** [comment]
All done, please test again and close this issue if all is good.
Else, please let me know :)

**Comment by thinkingmik** [comment]
Thank you Ken, now it's ok. 
Great job!

All the best to you and your team.
