### ISSUE TITLE
Query the value of a property associated with a command

### ISSUE THREAD

**Issue by a39172** [Fiware/context.Orion-LD#1377]
Consider the following property associated with a command:

`"deviceState_info": {
            "type": "Property",
            "value": {
                "@type": "commandResult",
                "@value": "OFF"
            },
            "observedAt": "2023-05-27T18:18:59.728Z"
}`

I want to get all entities that are off and I can't use the `q` parameter. This query never returns anything:

- `q=deviceState_info.@value=="OFF"`.

This one, for example, works:

- `deviceState_info.observedAt=="2023-05-27T18:18:59.728Z"`

I am using Orion 1.1.1.

Is this behavior normal?

**Comment by kzangeli** [comment]
Yes, that would be normal.
The dot is to tell the broker to look in sub-properties of the attribute (deviceState_info). To instead look inside a compound value, use []:

deviceState_info[@value] == "OFF"

**Comment by a39172** [comment]
> Yes, that would be normal. The dot is to tell the broker to look in sub-properties of the attribute (deviceState_info). To instead look inside a compound value, use []:
> 
> deviceState_info[@value] == "OFF"

That works. Thank you very much.
