### ISSUE TITLE
Entities with properties pointing at the same URI gets overwritten by the last one

### ISSUE THREAD

**Issue by JordiROP** [Fiware/context.Orion-LD#1400]
We are trying to create an schema to load it as a context in Orion-LD, inside the schema we have the following properties:

inletLiquidTemp:
  type: number
  description: "inlet liquid temp [C]"
  x-ngsi:
    uri: https://saref.etsi.org/saref4watr/FlowTemperature
outletLiquidTemp:
  type: number
  minimum: 0
  description: "Outlet liquid temp [C]"
  x-ngsi:
    uri-prefix: "[https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/"](https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/%22)

Both of them should point to the same uri -> uri: https://saref.etsi.org/saref4watr/FlowTemperature

But when we do this, Orion will substitute the name of the inletLiquidTemp and outletLiquidTemp for https://saref.etsi.org/saref4watr/FlowTemperature, and, when we create a subscription to store the updates in Quantu m Leap it creates a table with all the properties in the context, but, it will ignore the values of inletLiquidTemp, because both of them have been substituted for https://saref.etsi.org/saref4watr/FlowTemperature and will keep the latest received which belongs to outletLiquidTemp.

Is there any way of having both of the properties pointing at the same place? Can we avoid having the fields substituted, keeping its name?

**Comment by kzangeli** [comment]
I'm at a loss here, not sure what exactly you are trying to do.
If you edit the comment to clearly show the complete URL used, and the payload body as JSON, I'm sure I'll be able to help.

**Comment by JordiROP** [comment]
I have the following YAML this will be converted to a JSON-LD and used as a context when inserting data into Orion-LD.
As you can see there are two properties inside the CoolinTower entity pointing at the same URI:

inletLiquidTemp:
    type: number
    description: "inlet liquid temp [C]"
    x-ngsi:
      uri: https://saref.etsi.org/saref4watr/FlowTemperature
outletLiquidTemp:
    type: number
    minimum: 0
    description: "Outlet liquid temp [C]"
    x-ngsi:
      uri: https://saref.etsi.org/saref4watr/FlowTemperature

Both of them represents the same, but the first one is input and the second one is output, therefore we have thought on using the same uri as it works fine for describing the property.

The issue we have is that when we are inserting data, both properties are substituted with the uris as follows: 
  - inletLiquidTemp  becomes https://saref.etsi.org/saref4watr/FlowTemperature
  - outletLiquidTemp becomes https://saref.etsi.org/saref4watr/FlowTemperature

Then the context broker will only give value to only one property, as it will assume that both of them are the same, and this is happening because the name of the properties have been substituted with the URI.

My question is: Can I use the same URI to reference two different properties? Is there any way of telling ORION-LD to not change the name of the property with the reference stated in the URI?

I hope this is easier to understand, it is weird and a little bit difficult to make it clear.

Here you can find the yaml and the json used, Github will not let me attach JSON and YAML files.

YAML CONTEXT:
```yaml
---
    components:
      schemas:
        CoolingTower:
          description: "Cooling Tower\n"
          properties:
            dateObserved:
              $ref: "https://smart-data-models.github.io/dataModel.WaterQuality/WaterQualityObserved/model.yaml#/WaterQualityObserved/properties/dateObserved"
              x-ngsi:
                uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/"
            humidity:
              type: number
              description: "Humidity [%]"
              minimum: 0
              maximum: 100
              x-ngsi:
                uri: https://saref.etsi.org/saref4watr/Humidity
            inletAirTemp:
              type: number
              description: The degree or intensity of heat present in the air
              x-ngsi:
                uri: https://saref.etsi.org/saref4agri/AirTemperature
            inletLiquidTemp:
              type: number
              description: "inlet liquid temp [C]"
              x-ngsi:
                uri: https://saref.etsi.org/saref4watr/FlowTemperature
            outletLiquidTemp:
              type: number
              minimum: 0
              description: "Outlet liquid temp [C]"
              x-ngsi:
                uri: https://saref.etsi.org/saref4watr/FlowTemperature
            liquidFlowRate:
              type: number
              minimum: 0
              description: "Makeup water flow [M3/hr]"
              x-ngsi:
                model: https://schema.org/Number
                type: Property
                uri: https://saref.etsi.org/saref4watr/FlowVolume
            blowdown:
              type: number
              minimum: 0
              description: "blowdown [T/hr]"
              x-ngsi:
                model: https://schema.org/Number
                type: Property
                uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/"
            makeupWaterFlow:
              type: number
              minimum: 0
              description: "Makeup water flow [M3/HR]"
              x-ngsi:
                model: https://schema.org/Number
                type: Property
                uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/" 
            ventilators :
              items:
                properties:
                  id:
                    type: number
                    minimum: 0
                    description: "Ventilator ID"
                    x-ngsi:
                      model: https://schema.org/Number
                      type: Property
                      uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/ventilators/id"
                  powerConsumption:
                      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/saref-terms.yaml#/power"
                      x-ngsi:
                        uri: https://saref.etsi.org/core/Power
                  speed:
                    type: number
                    minimum: 0
                    description: "Percentage of fan speed"
                    x-ngsi:
                      model: https://schema.org/Number
                      type: Property
                      uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/ventilators/speed" 
              type: array
              description: "Ventilators of the cooling tower"
              x-ngsi:
                type: Property
                uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/CoolingTower/"
          type: object
          x-ngsi:
            uri-prefix: "https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.yaml#/"
    info: 
      description: "Data Models used within the AQUASPICE CS3B DOW"
      title: Basf-CSX
      version: "1.0.0"
    openapi: "3.0.0"
    paths: 
      /ngsi-ld/v1/entities: 
        get: 
          responses: 
            ? "200"
            : 
              content: 
                application/ld+json: 
                  schema: 
                    type: object
              description: OK
```

INSERT DATA
```json
{
        "id": "urn:ngsi-ld:AquaSpice:DOW:CoolingTower:CT3201",
        "type": "CoolingTower",
        "dateObserved": {
            "type": "Property",
            "value": {
                "@type": "DateTime",
                "@value": row['timestamp'].strftime("%Y-%m-%dT%H:%M:%SZ")
            }
        },
        "humidity": {
            "type": "Property",
            "value": row['CT3201 Humidity                      [%]']
        },
        "inletAirTemp": {
            "type": "Property",
            "value": row['CT3201 Inlet air temp                     [C]']
        },
        "inletLiquidTemp": {
            "type": "Property",
            "value": row['CT3201 inlet liquid temp      [C]']
        },
        "liquidFlowRate": {
            "type": "Property",
            "value": row['CT3201 Outlet/inlet liquid flow rate        [M3/hr]']
        },
        "makeupWaterFlow": {
            "type": "Property",
            "value": row['CT3201 Makeup water flow                     [M3/hr]']
        },
        "blowdown": {
            "type": "Property",
            "value": row['blowdown [T/hr]']
        },
        "outletLiquidTemp": {
            "type": "Property",
            "value": row['CT3201 Outlet liquid temp       [C]']
        },
        "ventilators": {
            "type": "Property",
            "value": ventilators
        },
        "@context": ["https://cs3b.rtm.aquaspice.eurecatprojects.com/schemas/AquaSPICE/CoolingTower/schema.jsonld"]
    }
```

**Comment by kzangeli** [comment]
ok, I now see the problem: 
> My question is: Can I use the same URI to reference two different properties?

I'm afraid the answer is no.
If the long name is the same, then the attribute is the same.
That's JSON-LD and nothing _I can do about that.

What you CAN do is to use two different aliases (shortnames) for the same long name, but, in two different contexts.
You said somewhere you wanted one shortname for queries and another shortname for creation/updates.
So, use two different contexts, one for queries and the other one for creation/update.
Would that make your life easier?
