### ISSUE TITLE
Orion-LD Subscription deleted subscriptions still visible

### ISSUE THREAD

**Issue by theguate** [Fiware/context.Orion-LD#1401]
**Issue Recreation Steps:**
1. Create one or two devices.
2. Create subscriptions to receive the notifications for each.
3. Delete all subscriptions. (/ngsi-ld/v1/subscriptions/urn:ngsi-ld:Subscription:IndoorEnvironment-AM103-xxx)
5. List all subscriptions after deletion. ( /ngsi-ld/v1/subscriptions) 
6. Observe the results: Sometimes the deleted subscriptions are still visible, while other times they are not. The issue seems intermittent when repeating the list operation.
7. Similar behavior if you one of the deleted subscriptions 

I encountered this issue while testing the subscription management functionality. It appears that the deletion of subscriptions does not consistently remove them from the list of subscriptions.
1st request.. /ngsi-ld/v1/subscriptions\urn:ngsi-ld:Subscription:IndoorEnvironment-WS302-2XXX
{
    "id": "urn:ngsi-ld:Subscription:IndoorEnvironment-WS302-24e124743c210336",
    "type": "Subscription",
    "description": "Notify me when sound is above LAeq 50",
    "entities": [
        {
            "type": "IndoorEnvironmentObserved"
        }
    ],

2nd Request /ngsi-ld/v1/subscriptions\urn:ngsi-ld:Subscription:IndoorEnvironment-WS302-2XXX
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
    "title": "subscription not found",
    "detail": "urn:ngsi-ld:Subscription:IndoorEnvironment-WS302-24e124743c210336"
}

If I append /ngsi-ld/v1/subscriptions?options=fromDb  the correct values are shown consistently.. 
 
**Additional Information:**
Deployed from AWS STF @alifrugal 
"Orion-LD version": "post-v1.1.0",

**Comment by kzangeli** [comment]
Ok. duly noted.
Thanks for reporting!
Seems like a bug in the subscription cache.
Question: are you using tenants?

**Comment by theguate** [comment]
/ngsi-ld/ex/v1/tenants nothing is shown, so I assume there are no tenants used in the environment.

**Comment by kzangeli** [comment]
Ok, thanks. I'll have a look tomorrow.
You're using undocumented non-NGSI-LD "features" ...
Have you been looking at the source code?
(I'm curious as to how you know about "fromDb" and the /ex/ url paths ...)

**Comment by theguate** [comment]
fromDb --> I was looking at other issues comments in this repo ( I think you show it as a workaround) . and since for me was looking like a cache issue , I was temped to try! and actually help me to review and validate the issue.. 
about the /ex/  you commented over here:  https://stackoverflow.com/questions/74641013/how-to-deal-with-ngsi-ld-tenants-create-list-delete
I'm very new on this topics.. I have read it before and I was looking if this was implemented in Ali's STF. but is pointing back to you! haha btw many thanks for your help! if fixed or any updates, will ask Ali to also update his repo.

**Comment by kzangeli** [comment]
Ok! I was just curious :)
I'll see if I can reproduce the issue first thing tomorrow and if so it should be quite easy to fix.
I'll let you know as soon as I know more

**Comment by kzangeli** [comment]
So, I created a functest that creates three subscriptions, GETs them, DELETEs them and then tries to GET them again.
All OK. I'm going to need some help here to try to reproduce the issue.
See [this functest](https://github.com/FIWARE/context.Orion-LD/blob/issue/1401/test/functionalTest/cases/0000_ngsild/ngsild_new_subscription_issue_1401.test) and help me make it look more like your test case.
If I can't reproduce, I can't fix.

But, first, could you please try with the latest Orion-LD image?

Cause, that's what I'm using.
I did fix a stupid bug in the subscription cache not long ago and ... not that I really think it's related but ...
Would be nice to test this against the newest version of the broker, even though it's not an "official release".

**Comment by theguate** [comment]
Hi Ken, just deployed "Orion-LD version": "post-v1.2.0". same issues over here. Will send a note with our URLs
in ECR https://gallery.ecr.aws/smart-territory-framework/orionld. it mentions 1.3, Ali have just update the image a few hour ago so maybe is something missing to update inside to show the version

**Comment by kzangeli** [comment]
ok.
In that case, edit a comment with the exact operations you do to reproduce the issue, see if I'm able as well.
See, I need it to fail in local, so I can run the broker inside gdb, add traces and run again, etc.
Just see the failure in an external broker doesn't help me much. 

Exact payload body and HTTP headers for POST /subscriptions, etc.  All of it.

**Comment by kzangeli** [comment]
Ah, just saw the email. All good

**Comment by kzangeli** [comment]
So, there are two issues here, all understood and good.
1. The deleted subscription survives:
    As an HA setup is in use, you need to turn on the sub-cache-refresh feature.
    This done by setting the CLI `-subCacheIval 3` (for a 3 sec refresh interval)    OR:
    `export ORIONLD_SUBCACHE_IVAL=3`
2. The notification fails.
    This is a bug, found and being fixed. The value of the HTTP Header "Host" is WRONG

**Comment by alifrugal** [comment]
Thanks Ken, I tested the notifications with the new version and I confirm it works now.  Also using the sub cache refresh feature, I also confirm the subscriptions are up to date now (after the time set in the env variable). 

All good, on my side, once the new version is pushed then I'll update the STF accordingly to point to the new one. 
Thanks for the support!
