### ISSUE TITLE
Fill datetime column Orion-LD TROE

### ISSUE THREAD

**Issue by JordiROP** [Fiware/context.Orion-LD#1426]
Hi,
I'm working with historical data and I'm trying to upload the data to Orion-LD, I have seen that enabling TROE it creates a group of columns and one of them is "datetime", could it be possible to fill this column with the original date like the observed date by adding some metadata to the entity at insertion time?
![image](https://github.com/FIWARE/context.Orion-LD/assets/17128072/a9f84f0d-890e-4ea2-8ca6-6d1f2e030fad)

something like:
{
        "id": "urn:ngsi-ld:Impetus:windSensor:Manresa",
        "type": "WindSensor",        
        "dateObserved": {
            "type": "Property",
            "value": date,
            "metadata": {
                "datetime": {
                    "type": "DateTime",
                    "value": date,
                }
        },
        "avg_speed":{
            "type": "Property",
            "value": avg_speed,
            "metadata": {
                "datetime": {
                    "type": "DateTime",
                    "value": date,
                }
        },
        "max_wind_gust": {
            "type": "Property",
            "value": max_wind_gust,
            "metadata": {
                "datetime": {
                    "type": "DateTime",
                    "value": date,
                }
        }        
        ,"@context": ["https://data-manager.climate-impetus.eu/schemas/WindSensor/schema.jsonld"]
    }

This way it would ease the filtering by date, enabling the filter by the original date of the data instead of the insertion date, which is not well suited for when we are working with historical data loaded from files.

Thanks a lot.

**Comment by JordiROP** [comment]
There is another column called ObservedAt and can be filled by adding "observedAt" inside a property.

**Comment by JordiROP** [comment]
The previous column can not be used to query data. Is there any plan of adding this feature in a near future?

**Comment by kzangeli** [comment]
Do you want to do historical queries over observedAt?
If so, that is the default temporal property, the other two being modifiedAt and createdAt (system attributes)
