### ISSUE TITLE
[Question] Should fully referenced types be valid? 

### ISSUE THREAD

**Issue by jason-fox** [Fiware/context.Orion-LD#143]
Thinking about it supplying a fully referenced data model in a query request should be valid:

```bash
curl -X GET \
  'http://localhost:1026/ngsi-ld/v1/entities?type=https://schema.org/Vehicle'
```

Because I am able to supply the context inline when I create

```json
{
  "id": "urn:ngsi-ld:Vehicle:car0001",
  "type": "Vehicle",
  ... etc.
  "@context": {
    "Vehicle": "https://schema.org/Vehicle"
  }
}
```

I shouldn't be forced to use the default context or supply a data model in the *Link* header at all times. I just want to retrieve the entities of a known type. Is this possible? Current implementation would return an empty array since the `@context` will expand and default to:

```text
https://default.uri/https://schema.org/Vehicle
```

Which is nonsensical, but appears to be the definition in the spec. Could the spec be updated to accommodate this?

**Comment by kzangeli** [comment]
In my opinion this makes sense.
The broker could just detect that the type value starts with `http://` or `htps://` and then verify it's a valid URL.
If so, we already have an FQN and no expansion would be performed.

However, we need to follow the spec so until this is discussed internally and with ETSI, this issue will be "on ice".

**Comment by kzangeli** [comment]
Experimental implementation (while decision pending) here: 
https://github.com/FIWARE/context.Orion-LD/pull/144

Note that the PR implements this feature for *one type* only.
for a list of types, the broker behaves as before.

When decision is made, either
1. Roll-back this change
2. Implement also for list of types (?list=T1.T2...Tn)

**Comment by jmcanterafonseca** [comment]
yes, we are adding this to the specification. A follow up

should we allow full type URIs in payloads as well? 

WDYT, @kzangeli @jason-fox ?

**Comment by jason-fox** [comment]
@kzangeli - can this be closed?

**Comment by kzangeli** [comment]
We do allow FQN for entity types.
So yes, we can close this issue.
