### ISSUE TITLE
links in attributes again

### ISSUE THREAD

**Issue by DasNordlicht** [Fiware/context.Orion-LD#1439]
Moin Ken,
with the 1.4.0 we suddenly have links in the attributes again, what are we doing wrong again?

`    "owner": {
        "type": "Property",
        "value": "urn:ngsi-ld:Qwner:captn"
    },
    "https://uri.etsi.org/ngsi-ld/name": {
        "type": "Property",
        "value": "boening:AHD-DPS02"
    },
    "https://uri.etsi.org/ngsi-ld/description": {
        "type": "Property",
        "value": "boening:AHD-DPS02"
    },
    "dateCreated": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2023-09-05T12:14:38.058Z"
        }
    },`

**Comment by kzangeli** [comment]
ok, that seems to depend on the core context.
Starting in v1.4, Orion-LD now uses the version 1.6 of the core context.
name and description are no longer part of the core context ion v1.6.
There's a CLI option that allows you to pick another version, you might prefer the v1.0 of the core context:
```
     [option '-coreContext' <Core context version (v1.0|v1.3|v1.4|v1.5|v1.6|v1.7) - v]   ORIONLD_CORE_CONTEXT                'v1.6' /'v1.6'/                                    (default value)
```
ORIONLD_CORE_CONTEXT is the name of the env var

**Comment by DasNordlicht** [comment]
Thx, we will test it

**Comment by DasNordlicht** [comment]
hm, unfortunately does not work  :-(

    Environment:                                                                                                                                                                                                                              
      ORIONLD_CORE_CONTEXT:       v1.4                                                                                                                                                                                                        
      ORIONLD_MONGO_REPLICA_SET:  rs0                                                                                                                                                                                                         
      ORIONLD_MONGO_USER:         root                                                                                                                                                                                                        
      ORIONLD_MONGO_TIMEOUT:      4000                                                                                                                                                                                                        
      ORIONLD_MONGO_POOL_SIZE:    15                                                                                                                                                                                                          
      ORIONLD_MONGO_ID_INDEX:     TRUE                                                                                                                                                                                                        
      ORIONLD_STAT_COUNTERS:      TRUE                                                                                                                                                                                                        
      ORIONLD_STAT_SEM_WAIT:      TRUE                                                                                                                                                                                                        
      ORIONLD_STAT_TIMING:        TRUE                                                                                                                                                                                                        
      ORIONLD_SUBCACHE_IVAL:      60 
      
But how do we solve this for existing entities if we want to upgrade to v1.6 at some point?

Do we have to create a local context for this?
That can't be the purpose that such attributes are suddenly no longer available in the core context.

Which Core Context version was set in Orion-LD 1.2.1?

**Comment by kzangeli** [comment]
Try the oldest one "v1.0", that's what Orion-LD used before this update.  I'm not sure when "name" and "description" were rmoved/modified.

**Comment by kzangeli** [comment]
> But how do we solve this for existing entities if we want to upgrade to v1.6 at some point?

In a perfect world, I'd provide a script to merge your database.
It's simply to change all old long names to their new values.
Shouldn't be too hard but I'm swamped right now and for the next few years ... :)
We'll deal with that when we get there.

**Comment by DasNordlicht** [comment]
ok v1.0 works

**Comment by kzangeli** [comment]
> ok v1.0 works

Good. Keep using that ... forever? :)
Just joking. Let me know if you see the need to change the core context.

**Comment by DasNordlicht** [comment]
what would we have to do if we want to switch to the new context?

Is there a manual or a function that does this?
Or do we really have to adjust the attributes manually in MongoDB?

change  "https://uri.etsi.org/ngsi-ld/name", to  "name",
```
    "attrNames" : [
        "https://uri.etsi.org/ngsi-ld/name",
        "https://uri.etsi.org/ngsi-ld/default-context/manufacturer",
        "https://uri.etsi.org/ngsi-ld/default-context/documentation",
        "https://uri.etsi.org/ngsi-ld/default-context/lampOutputsArray",
        "https://uri.etsi.org/ngsi-ld/default-context/communicationBuses",
        "https://uri.etsi.org/ngsi-ld/default-context/relayOutputs",
        "https://uri.etsi.org/ngsi-ld/default-context/modbusOption",
        "https://uri.etsi.org/ngsi-ld/default-context/powerSupplyVoltage",
        "location",
        "https://uri.etsi.org/ngsi-ld/status",
        "https://uri.etsi.org/ngsi-ld/default-context/energie",
        "https://uri.etsi.org/ngsi-ld/default-context/systemFailure",
        "https://uri.etsi.org/ngsi-ld/default-context/emergencyMode",
        "https://uri.etsi.org/ngsi-ld/default-context/address",
        "https://uri.etsi.org/ngsi-ld/default-context/owner",
        "https://uri.etsi.org/ngsi-ld/default-context/dateObserved",
        "https://uri.etsi.org/ngsi-ld/default-context/dateLastValueReported"
    ],
```
and also by the attrs
```
    "attrs" : {
        "https://uri=etsi=org/ngsi-ld/name" : {
            "type" : "Property",
            "creDate" : 1694158558.782028,
            "modDate" : 1694158558.782028,
            "value" : "Grundmodul für Positions- und Signallaternensteuerung und -überwachung DPS02",
            "mdNames" : [

            ]
        },
```
or is there an easier way?

**Comment by kzangeli** [comment]
First of all, you don't really need to switch contexts. Just start the broker with v1.0 and you're good.

If you really really want to go with the newest context, it's not like it's a hard thing to modify the DB for this to work.
I just don't have the bandwidth to implement the necessary script/executable for it right now.

What you'd need to do is modify all those long names in "attrs" (with dots replaced with '=') and "attrNames" (with dots), for the new long names.

Core Context v1.6 (which is now the default for Orion-LD) defines:
   "description": "http://purl.org/dc/terms/description"

"name" on the other hand has been removed from the Core Context, as it is no longer a defined term in NGSI-LD.
It's up to you to pick a longname for "name" - it all depends on your data model.
If you don't use a specific data model for "name", you can always expand using @vocab from the core context.
It would look like this:  
`https://uri.etsi.org/ngsi-ld/default-context/name"`

If you have any doubts, just let me know and we can do an audio.

**Comment by DasNordlicht** [comment]
we will test this on occasion, currently we live in the 1.0 world ;-)
The next tenant will then be built on 1.6.

**Comment by kzangeli** [comment]
So. I think this issue can be closed.
Reopen if needed
