### ISSUE TITLE
Error when trying to replicate an entity using an inclusive registration

### ISSUE THREAD

**Issue by ravaga** [Fiware/context.Orion-LD#1456]
I have deployed two dockerized Orion-LD instances (accessible via ports 1026 and 1027 of the same machine) because I want to replicate an entity in another broker to act as a backup. However, the replication isn't working and Orion returns a 207 HTTP status code when I try to create an entity. These are the steps I've followed:

1.  Create a context source registration in the Orion A (port 1026) using this body:

```json
{
    "id": "urn:R1",
    "type": "ContextSourceRegistration",
    "information": [
        {
            "entities": [
                {
                    "type": "IE"
                }
            ]
        }
    ],
    "endpoint": "192.168.1.124:1027",
    "mode": "inclusive",
    "operations": [
        "updateOps",
        "redirectionOps"
    ]
}
```

2.  Create an entity in the Orion A using this body:

```json
{
  "id": "urn:ngsi-ld:IE:001",
  "type": "IE",
  "domain": {
    "type": "Relationship",
    "object": "urn:ngsi-ld:Domain:01"
  },
  "totalRAM": {
    "type": "Property",
    "value": 32
  },
  "cPUCores": {
    "type": "Property",
    "value": 4
  },
  "avgPowerConsumption": {
    "type": "Property",
    "value": 50
  },
  "realTimeCapable": {
    "type": "Property",
    "value": true
  },
  "currentRAM": {
    "type": "Property",
    "value": 45
  },
  "currentCPUUsage": {
    "type": "Property",
    "value": 2
  },
  "currentPowerConsumption": {
    "type": "Property",
    "value": 9
  }
}
```

3. This is body of the response to the entity creation request, with an _207 Multi-status_ HTTP status code:

```json
{
    "entityId": "urn:ngsi-ld:IE:001",
    "updated": [
        "avgPowerConsumption",
        "cPUCores",
        "currentCPUUsage",
        "currentPowerConsumption",
        "currentRAM",
        "domain",
        "realTimeCapable",
        "totalRAM"
    ],
    "notUpdated": [
        {
            "registrationId": "urn:R1",
            "statusCode": 400,
            "title": "Duplicated field",
            "detail": "id",
            "attributes": [
                "domain",
                "totalRAM",
                "cPUCores",
                "avgPowerConsumption",
                "realTimeCapable",
                "currentRAM",
                "currentCPUUsage",
                "currentPowerConsumption"
            ]
        }
    ]
}
```

The entity has been created in the Orion A, but not in the Orion B (port 1027). Furthermore, if I try to update the _realTimeCapable_ attribute in the Orion A (HTTP PATCH request to http://192.168.1.124:1026/ngsi-ld/v1/entities/urn:ngsi-ld:IE:001/attrs/realTimeCapable), an HTTP 500 is returned and the Orion B crashes.

```json
{
    "type": "Property",
    "value": false
}
```

**Comment by kzangeli** [comment]
ok, thanks for reporting!

I have managed to reproduce the error and apparently, the entity id and type are added not once but TWICE to the payload body that is forwarded!

So, the second broker receives the creation request, but it errors out due to "duplicated field".
Stupid bug, should be easy to fix.

**Comment by ravaga** [comment]
Thanks Zen for your quick fix
