### ISSUE TITLE
Error when retrieving entities by type in federated operations (forwarding mode)

### ISSUE THREAD

**Issue by ravaga** [Fiware/context.Orion-LD#1466]
I have deployed two dockerized Orion-LD instances (accessible via ports 1026 -Orion A- and 1027 -Orion B- of the same machine) to perform some tests about new forwarding features. The idea is to create a Context Source Registration to obtain all the entities of one type by only calling to one Orion instance, but the broker crashes. These are the steps I've followed:

1.  Create two entities in the Orion A (port 1026) using these bodies:

```json
{
  "id": "urn:E1",
  "type": "T",
  "P1": "Entity E1 in Orion A",
  "R1": { "object": "urn:E2" }
}
```
```json
{
  "id": "urn:E2",
  "type": "T",
  "P1": "Entity E2 in Orion A",
  "R1": { "object": "urn:E1" }
}
```

2.  Create two entities in the Orion B (port 1027) using these bodies:
```json

{
  "id": "urn:E3",
  "type": "T",
  "P1": "Entity E3 in Orion B",
  "R1": { "object": "urn:E4" }
}
```
```json
{
  "id": "urn:E4",
  "type": "T",
  "P1": "Entity E4 in Orion B",
  "R1": { "object": "urn:E3" }
}
```

3.  Create an inclusive context source registration in the Orion A (port 1026) using this body:
```json
{
  "id": "urn:R1",
  "type": "ContextSourceRegistration",
  "information": [
    {
      "entities": [
        {
          "type": "T"
        }
      ]
    }
  ],
  "mode": "inclusive",
  "operations": [ "retrieveOps" ],
  "endpoint": "http://192.168.1.124:1027"
}
```

4.  Obtain all the entities of type _T_ through an HTTP GET request to Orion A

``` 
curl --location 'http://192.168.1.124:1026/ngsi-ld/v1/entities?type=T'
``` 

Then Orion A crashes...

**Comment by ravaga** [comment]
It seems to be due to I have entities of type _T_ in both brokers, because if I only create entities of type _T_ in Orion B, it works properly.

Furthermore, if I only create entities of type _T_ in Orion B, but after creating the Context Source registration I create entities of type _T_ in the Orion A, it doesn't crash... However, the local entities of type _T_ of Orion A are not returned. In addition, the _Entity-Map_ HTTP header is also not being returned in the response.

**Comment by ravaga** [comment]
Thanks Ken, the described issue has been fixed. However, I found a related issue when I was testing the former. Now, in the step number 4 the broker returns the 4 entities as expected, along with the HTTP Headers _Entity-Map_ (with a value: _urn:ngsi-ld:entity-map:bafd70b6-82da-11ee-9aba-0242c0a8b003_) and _NGSILD-Results-Count_ (with a value of 4, which is correct).

```bash
curl --location 'http://192.168.1.124:1026/ngsi-ld/v1/entities?type=T&count=true'
```

After it, I create two more entities (one in Orion A and one in Orion B) to check if the results are updated.

5. Create an entity in the Orion A (port 1026) using this body:
```json
{
  "id": "urn:E5",
  "type": "T",
  "P1": "Entity E5 in Orion A",
  "R1": { "object": "urn:E2" }
}
```

6. Create an entity in the Orion B (port 1027) using this body:
```json
{
  "id": "urn:E6",
  "type": "T",
  "P1": "Entity E6 in Orion B",
  "R1": { "object": "urn:E4" }
}
```

7. Obtain all the entities of type T through an HTTP GET request to Orion A
```bash
curl --location 'http://192.168.1.124:1026/ngsi-ld/v1/entities?type=T&count=true'
```

**Result**: Orion A returns all the entities of type _T_ except the new entity _urn:E5_ created in the Orion A (step 5). In addition, the HTTP Header _Entity-Map_ is not returned (I think it should be returned because two more entities have been created so the query result has been modified), and the HTTP Header _NGSILD-Results-Count_ is stuck with the former value (its value must be 6, but is returned a value of 4).

```json
[
    {
        "id": "urn:E1",
        "type": "T",
        "P1": {
            "type": "Property",
            "value": "Entity E1 in Orion A"
        },
        "R1": {
            "type": "Relationship",
            "object": "urn:E2"
        }
    },
    {
        "id": "urn:E2",
        "type": "T",
        "P1": {
            "type": "Property",
            "value": "Entity E2 in Orion A"
        },
        "R1": {
            "type": "Relationship",
            "object": "urn:E1"
        }
    },
    {
        "id": "urn:E3",
        "type": "T",
        "P1": {
            "type": "Property",
            "value": "Entity E3 in Orion B"
        },
        "R1": {
            "type": "Relationship",
            "object": "urn:E4"
        }
    },
    {
        "id": "urn:E4",
        "type": "T",
        "P1": {
            "type": "Property",
            "value": "Entity E4 in Orion B"
        },
        "R1": {
            "type": "Relationship",
            "object": "urn:E3"
        }
    },
    {
        "id": "urn:E6",
        "type": "T",
        "P1": {
            "type": "Property",
            "value": "Entity E6 in Orion B"
        },
        "R1": {
            "type": "Relationship",
            "object": "urn:E4"
        }
    }
]
```

**Comment by kzangeli** [comment]
So ... how do I explain all this ... ? :)
This is still kind of open in ETSI ISG CIM, we actually discussed exactly this in this morning's API call.
In the first call, the entityMap is returned because it was created. In consecutive calls using the same entity map, no map is returned as it hasn't been created.

Also, any new entity, created after the entityMap was created must not be included in the response. Any response using that entityMap.  When the entityMap is created, the list of matching entities is frozen - meaning, the broker creates the entity map, containing all the entities that matched the initial query (when the map was created)

This is quite complex. I might have to explain all this in a call ...

Just let me know and we'll set up a meeting.

**Comment by ravaga** [comment]
Understood Ken, I'm closing the issue
