### ISSUE TITLE
Orion-LD trims long Headers in forwarded requests 

### ISSUE THREAD

**Issue by ravaga** [Fiware/context.Orion-LD#1525]
I'm using Krakend API Gateway, which checks JWT tokens created in Keycloak, in front an Orion-LD instance to protect it. On the other side, I also have another Orion-LD instance and I want to create a Context Source Registration in it to also obtain entities of type T from the _protected_ broker. This is the body of the registration:

```json
{
  "id": "urn:R1",
  "type": "ContextSourceRegistration",
  "information": [
    {
      "entities": [
        {
          "type": "T"
        }
      ]
    }
  ],
  "contextSourceInfo": [
    {
      "key": "Authorization",
      "value": "urn:ngsi-ld:request"
    }
  ],
  "mode": "inclusive",
  "operations": [ "retrieveOps"],
  "endpoint": "http://krakend/orion",
  "hostAlias": "protectedOrion"
}
```

After creating the registration, I make an HTTP GET request to the unprotected Orion (adding the _Authorization_ header with a valid token) to obtain entities of type T from both brokers. However, I only receive the entities from the protected broker.

Checking the logs, I can see that the forwarded request returns a _401 Unauthorized_ status, so there is a problem in the Authorization headers. Therefore, when I check the value of this auth header, I discover that **Orion is actually trimming the value of the header** in the forwarded request.

**Comment by ravaga** [comment]
Find here an example of the **original Authorization header**:

`Bearer auJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCT0JsSEliWlV1ZHFydmpPQjZXbktBaHlFdU1IdWViZ2RkOXNKS3U5RWNFIn0.eyJleHAiOjE3ODk0OTE4MjEsImlhdCI6MTcwMzE3ODIyMSwianRpIjoiODFlNmVmNTktZTExZC00YjI1LWE5ZTAtZWNhNDQzNDkxYTBlIiwiaXNzIjoiaHR0cDovLzE1OC40Mi4xNjEuMTc3OjMxNTUxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6WyJtYXN0ZXItcmVhbG0iLCJhY2NvdW50Il0sInN1YiI6IjU2NjAwOWQ3LWJlMWUtNGYxZC05OWY2LTdiMjBkZmVlMDAyZiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFlcm9zIiwic2Vzc2lvbl9zdGF0ZSI6ImNkZTk5OTQ2LTUwM2UtNDY2OS04NDU2LTdlMjhhODQ2MzdhOSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY3JlYXRlLXJlYWxtIiwiZGVmYXVsdC1yb2xlcy1tYXN0ZXIiLCJvZmZsaW5lX2FjY2VzcyIsImFkbWluIiwiZG9tYWluX2FkbWlucyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWVyb3MiOnsicm9sZXMiOlsidXB2X3JvbGVfMSJdfSwibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctcmVhbG0iLCJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJjZGU5OTk0Ni01MDNlLTQ2NktODQ1Ni03ZTI4YTg0NjM3YTkiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFlcm9zX3VzZXJfMiIsImdpdmVuX25hbWUiOiIiLCJmYW1pbHlfbmFtZSI6IiJ9.VDnNuP497t7SjYlXzCWaWUw33e3OPwLpB0xqCsOgekgwBySuaUpqJ6xaCssrmdgx8WYg3EE76GdcvnKSkC1oeTiR49AeKXK3DUE8uj60zZKwXwQVapP7LhowraQpGeiwirGDZc9DV5at8pMR2gH3c88KSVtudxJQUcwm7wt0qvlX0M1eDJOo4YYjs41mIQiBWmIxantt3qXapk7ZzyByp3sp2Kzo6wJVAcJRlkoIsXBxAh6n5D1gerJzwh0f5OZMpxgjwCF3Jjps4Wjkh0je-CHFF-x0cSIS_LsqbPgys--mmuxyeXUF4W1wI2WyW36glEkCDdnZpbGhQXqtpFlxg`

and the value of the **header that Orion is actually forwarding** to Krakend:

`Bearer auJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCT0JsSEliWlV1ZHFydmpPQjZXbktBaHlFdU1IdWViZ2RkOXNKS3U5RWNFIn0.eyJleHAiOjE3ODk0OTE4MjEsImlhdCI6MTcwMzE3ODIyMSwianRpIjoiODFlNmVmNTktZTExZC00YjI1LWE5ZTAtZWNhNDQzNDkxYTBlIiwiaXNzIjoiaHR0cDovLzE1OC40Mi4xNjEuMTc3OjMxNTUxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6WyJtYXN0ZXItcmVhbG0iLCJhY2NvdW50Il0sInN1YiI6IjU2NjAwOWQ3LWJlMWUtNGYxZC05OWY2LTdiMjBkZmVlMDAyZiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFlcm9zIiwic2Vzc2lvbl9zdGF0ZSI6ImNkZTk5OTQ2LTUwM2UtNDY2OS04NDU2L`

**Comment by kzangeli** [comment]
The broker was using a max length of 512 bytes for HTTP headers.
Clearly that's not good enough. Easy fix, see https://github.com/FIWARE/context.Orion-LD/commit/ef0d5fbded3c0f36d58b9ef6d66e574b205ad526

**Comment by ravaga** [comment]
Solved, Orion-LD no longer trims long HTTP headers so the authentication is performed properly.
