### ISSUE TITLE
KeyValues option is not working when retrieving federated entities

### ISSUE THREAD

**Issue by ravaga** [Fiware/context.Orion-LD#1551]
I have 3 Orion-LD federated instances through Context Source Registrations. When I make an HTTP GET request (/ngsi-ld/v1/entities?options=keyValues&type=T) to obtain all the entities of the type T in key-values format, only local entities of the broker are returned in this format. The entities that belong to the other brokers are returned in the default normalized format.

**Comment by kzangeli** [comment]
ok, that's unfortunate :)
I'll look into this asap,

**Comment by kzangeli** [comment]
See also https://github.com/FIWARE/context.Orion-LD/pull/1555   (fix for crash with format=concise)

**Comment by ravaga** [comment]
After performing some tests using `format=simplified` , it's working as expected. The same applies for the _concise_ format related bug.

**Comment by ravaga** [comment]
The same bug occurs when retrieving a single entity using its ID `GET /ngsi-ld/v1/entities/urn:ngsi-ld:E1?format=simplified` and also with `options=keyValues`
