### ISSUE TITLE
Orion-CB container crash when trying to access entity with relationship type object set to 'None' (python None used)

### ISSUE THREAD

**Issue by vpitsilis** [Fiware/context.Orion-LD#1589]
In an Orion-CB running as a container deployment.
Updated, within an existing entity, a relationship object using Python None value. 

The update was placed using PATCH method, to the entity URL: `{base_url}/enities/{entity_id}`.
The object used for update (python), was that:
`  data = {
        "infrastructureElement": {
            "type": "Relationship",
            "object": None
     }`

After that when trying to access the specific entity or even get all entities (`ServiceComponent` was the type of the entity) list the Orion-CB crashed. 
A 500 Internal Error was returned to the subsequent (related) entities request and the container crashed.

Screenshot of the container failing when receiving a request related to updated entity type:
![image](https://github.com/FIWARE/context.Orion-LD/assets/33813328/91b17a65-a3b4-43c9-8a17-a43ff02ac644)

**Comment by kzangeli** [comment]
So, I ran a test.
1. Did not get any crash
2. PATCHing with `"object": null` gives a 204 but doesn't do anything.
    That's not good, it should give an error (null is not valid for JSON-LD). But, at least it doesn't affect the entity. Still a bug
3. PATCHing with `"object": "urn:ngsi-ld:null"` works just fine - that special string is how NGSI-LD overcomes the problem with
    normal JSON null that is not allowed in JSON-LD.

I'd love to be able to reproduce the crash, so I could fix it ...
That said, the solution to this issue is to not use `null` but `"urn:ngsi-ld:null"`

**Comment by vpitsilis** [comment]
> So, I ran a test.
> 
> 1. Did not get any crash
> 2. PATCHing with `"object": null` gives a 204 but doesn't do anything.
>    That's not good, it should give an error (null is not valid for JSON-LD). But, at least it doesn't affect the entity. Still a bug
> 3. PATCHing with `"object": "urn:ngsi-ld:null"` works just fine - that special string is how NGSI-LD overcomes the problem with
>    normal JSON null that is not allowed in JSON-LD.
> 
> I'd love to be able to reproduce the crash, so I could fix it ... That said, the solution to this issue is to not use `null` but `"urn:ngsi-ld:null"`

thanks, `"urn:ngsi-ld:null"` works nice

**Comment by kzangeli** [comment]
I believe this issue is fixed, closing it.
@vpitsilis , if you don't agree, go ahead and reopen it.
