### ISSUE TITLE
Create Entity with LD Context fails

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#16]
Error:

`
{"body": {"details": "https://fiware.github.io/NGSI-LD_Tests/ldContext/testFullContext.jsonld", "title": "failure to create context from URL", "type": "http://example.org/ngsi-ld/errors/BadRequestData"}, "headers": {"connection": "close", "content-length": "188", "content-type": "application/json", "date": "Tue, 20 Nov 2018 16:50:38 GMT"}, "request": {"headers": {"Content-Type": "application/ld+json", "accept": "application/json", "content-length": 307}, "method": "POST", "uri": {"auth": null, "hash": null, "host": "localhost:1030", "hostname": "localhost", "href": "http://localhost:1030/ngsi-ld/v1/entities/", "path": "/ngsi-ld/v1/entities/", "pathname": "/ngsi-ld/v1/entities/", "port": "1030", "protocol": "http:", "query": null, "search": null, "slashes": true}}, "statusCode": 400}
`

**Comment by jmcanterafonseca** [comment]
Tests that fail:

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextProvision/create_entity_with_ldcontext_test.js#L16

**Comment by kzangeli** [comment]
This seems to be a network problem:  `failure to create context from URL`.
Try again, see if it works, and make sure that `https://fiware.github.io/NGSI-LD_Tests/ldContext/testFullContext.jsonld` is visible.

**Comment by jmcanterafonseca** [comment]
closing. Now the Docker container includes all the certificates needed to resolve remote @context
