### ISSUE TITLE
MIME Type is not respected

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#160]
using 

```
{
    "@context": "https://forge.etsi.org/gitlab/NGSI-LD/NGSI-LD/raw/master/defaultContext/defaultContext.jsonld",
    "branch": "(HEAD",
    "kbase version": "0.2",
    "kalloc version": "0.2",
    "kjson version": "0.2",
    "boost version": "1_62",
    "microhttpd version": "0.9.48-0",
    "openssl version": "OpenSSL 1.1.0k  28 May 2019",
    "mongo version": "1.1.3",
    "rapidjson version": "1.0.2",
    "libcurl version": "7.52.1",
    "libuuid version": "UNKNOWN",
    "Next File Descriptor": 18
}
```

```
curl -X POST \
  http://localhost:1030/ngsi-ld/v1/entities/ \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/ld+json' \
  -H 'Host: localhost:1030' \
  -H 'Postman-Token: bc0cfc76-4feb-4aac-aaa5-9229905cd02e,56135689-c4f4-46a8-88d1-42851b98fbbe' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 916' \
  -d '{
    "id": "urn:ngsi-ld:Building:store002",
    "type": "Building",
    "category": {
        "type": "Property",
        "value": ["commercial"]
    },
    "address": {
        "type": "Property",
        "value": {
            "streetAddress": "Friedrichstraße 44",
            "addressRegion": "Berlin",
            "addressLocality": "Kreuzberg",
            "postalCode": "10969"
        },
        "verified": {
            "type": "Property",
            "value": true
        }
    },
     "location": {
        "type": "GeoProperty",
        "value": {
             "type": "Point",
              "coordinates": [13.3903, 52.5075]
        }
    },
    "name": {
        "type": "Property",
        "value": "Checkpoint Markt"
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
        "https://schema.lab.fiware.org/ld/fiware-datamodels-context.jsonld"
    ]
}'
```

201 OK

Then

```
curl -X GET \
  'http://localhost:1030/ngsi-ld/v1/entities/?type=Building' \
  -H 'Accept: application/json' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: localhost:1030' \
  -H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
  -H 'Postman-Token: fc8edb97-40a1-4d21-9b64-b3a991800109,66e5101b-4769-49e4-8b87-04b4c8076950' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache'
```

result is 

Headers:

```
Connection →Keep-Alive
Content-Length →509
Content-Type →application/ld+json
Date →Thu, 01 Aug 2019 09:33:32 GMT
```
```
[
    {
        "@context": "https://schema.lab.fiware.org/ld/context",
        "id": "urn:ngsi-ld:Building:store002",
        "type": "Building",
        "address": {
            "type": "Property",
            "value": {
                "streetAddress": "Friedrichstraße 44",
                "addressRegion": "Berlin",
                "addressLocality": "Kreuzberg",
                "postalCode": "10969"
            },
            "verified": {
                "type": "Property",
                "value": true
            }
        },
        "name": {
            "type": "Property",
            "value": "Checkpoint Markt"
        },
        "category": {
            "type": "Property",
            "value": [
                "commercial"
            ]
        },
        "location": {
            "type": "GeoProperty",
            "value": {
                "type": "Point",
                "coordinates": [
                    13.3903,
                    52.5075
                ]
            }
        }
    }
]
```

incorrect. it should be `application/json` withouth the `@context` in the payload.

**Comment by jason-fox** [comment]
Does this imply:

* Header`Accept: *` - ~JSON and `@context` returned~  JSON only and @context returned in the Link Header.
* Header`Accept: application/ld+json` - JSON and `@context` returned in body
* Header `Accept: application/json` - JSON only - ~no `@context`~ @context returned in the Link Header.
* Header `Accept: application/ld` - ~`@context` only - no JSON~ **Error 406 Not Acceptable** - not a mime type.
* Header `Accept: text/html,application/xhtml+xml` -  **Error 406 Not Acceptable**

Also precedence headers:
* Header `Accept: application/json, application/ld+json;q=0.9, */*;q=0.8` = JSON only and @context returned in the Link Header.
* Header `Accept: application/json+ld, application/json;q=0.9, */*;q=0.8` = JSON and `@context` in body

**Note:** `Accept` header errors should consistently result in **406** error codes.

**Comment by jmcanterafonseca** [comment]
> Does this imply:
> 
> * Header`Accept: *` - JSON and `@context` returned  

`Accept: */*` is under discussion. Ken's opinion is that it should imply JSON-LD. @jason-fox what do you think?

> * Header`Accept: application/ld+json` - JSON and `@context` returned 
* Header`Accept: application/ld+json` - JSON and `@context` returned in payload
> * Header `Accept: application/json` - JSON only - no `@context`
* Header `Accept: application/json` - JSON only - no `@context`. Returned in the Link Header. 
> * Header `Accept: application/ld` - `@context` only - no JSON

`application/ld` is not valid MIME type


no Accept Header: `application/json` 

> Also precedence headers:
> 
> * Header `Accept: application/json, application/ld+json;q=0.9, */*;q=0.8` = JSON only
> * Header `Accept: application/json+ld, application/json;q=0.9, */*;q=0.8` = JSON and `@context`

**Comment by jason-fox** [comment]
* Header `Accept: text/html,application/xhtml+xml` -  **Error 406 Not Acceptable**

**Comment by jmcanterafonseca** [comment]
yes, the spec says Unsupported Media Type, that shall result in just a 415

**Comment by jason-fox** [comment]
```console
curl -X POST \
  http://localhost:1030/ngsi-ld/v1/entities/ \
  -H 'Accept: */*' \
  -H 'Content-Type: application/ld+json' \
...etc
```
Is a valid upload request.

- `Content-Type:  application/xhtml+xml` should *415 Unsupported Media Type*

What about 

- `Content-Type:  application/json` - is this *415* or can the `@context` be supplied by a `Link` header?

**Comment by jmcanterafonseca** [comment]
> ```
> curl -X POST \
>   http://localhost:1030/ngsi-ld/v1/entities/ \
>   -H 'Accept: */*' \
>   -H 'Content-Type: application/ld+json' \
> ...etc
> ```
> 
> Is a valid upload request.
> 
> * `Content-Type:  application/xhtml+xml` should _415 Unsupported Media Type_
> 
> What about
> 
> * `Content-Type:  application/json` - is this _415_ or can the `@context` be supplied by a `Link` header?

`@context` can be supplied via Link Header

**Comment by jason-fox** [comment]
So for an Upload, `Content-Type: application/json` plus `Link Header` is good.
What about an upload with: 
- `Content-Type: application/json` **without** a `Link Header` ?
- `Content-Type: application/json` **with** an **@context** in the body - i.e. supply LD but claiming it is plain JSON

**Comment by jmcanterafonseca** [comment]
> So for an Upload, `Content-Type: application/json` plus `Link Header` is good.
> What about an upload with:
> 
> * `Content-Type: application/json` **without** a `Link Header` ?


The Entity will fallback into the Default @context

> * `Content-Type: application/json` **with** an **@context** in the body - i.e. supply LD but claiming it is plain JSON

400 Error

**Comment by kzangeli** [comment]
PR with functest: https://github.com/FIWARE/context.Orion-LD/pull/161
Everything seems to be just fine ...
Tested in Ubuntu 18.04 and CentOS 7.

**Comment by jmcanterafonseca** [comment]
@jason-fox is that happening to you?

**Comment by jason-fox** [comment]
![Screenshot 2019-08-01 at 14 06 47](https://user-images.githubusercontent.com/3439249/62292081-d3d29280-b465-11e9-94ad-b0d806f84d5b.png)

Taken from the [Linked Data Tutorial](https://github.com/FIWARE/tutorials.Linked-Data). Created an entity and queried for it as shown.

* *Accept* header in the request states `application/json`
* *Content-type* returned states `application/ld+json`

**Comment by jason-fox** [comment]
@jmcanterafonseca @kzangeli - Looks like this could be *Postman*:

```console
 curl -iX GET \
  'http://localhost:1026/ngsi-ld/v1/entities/?type=Building&q=name==%27Checkpoint%20Markt%27&options=keyValues' \
   -H 'Accept: application/json' \
   -H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' 
```

Returns
```text
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 296
Content-Type: application/json
Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
Date: Thu, 01 Aug 2019 12:22:31 GMT
```
```json
[
  {
    "id": "urn:ngsi-ld:Building:store002",
    "type": "Building",
    "address": {
      "streetAddress": "Friedrichstraße 44",
      "addressRegion": "Berlin",
      "addressLocality": "Kreuzberg",
      "postalCode": "10969"
    },
    "name": "Checkpoint Markt",
    "category": [
      "commercial"
    ],
    "location": {
      "type": "Point",
      "coordinates": [
        13.3903,
        52.5075
      ]
    }
  }
]
```

**Comment by jmcanterafonseca** [comment]
fixed at last!
