### ISSUE TITLE
State of context server

### ISSUE THREAD

**Issue by fbuedding** [Fiware/context.Orion-LD#1653]
What is the state of the context server? Are the contexts persisted in the newest version?

The documentation is stating it may be fixed in v0.9
https://github.com/FIWARE/context.Orion-LD/blob/27149acef3f1d2d64fc702a40367f8c70e619d04/doc/manuals-ld/contextServer.md?plain=1#L8-L9

Thank you!

**Comment by kzangeli** [comment]
Yes, that was implemented long time ago, I'd say well over a year ago

**Comment by fbuedding** [comment]
Thank you!
