### ISSUE TITLE
Request for the implementation of the "idPattern" parameter in distributed GET /entities requests

### ISSUE THREAD

**Issue by ravaga** [Fiware/context.Orion-LD#1688]
The **idPattern** query parameter in the `GET /entities` endpoint doesn't seem to be implemented for distributed requests (when some Context Source Registrations are present in the Context Broker). This parameter works as expected when only the local entities are taken into consideration (`local=true`).

Please @kzangeli , could you implement it?

**Comment by kzangeli** [comment]
But of course.
Should be done this week.

**Comment by kzangeli** [comment]
Implemented. Please test and let me know

**Comment by ravaga** [comment]
Thanks Ken, I've tested it both using a simple idPattern to filter out entities whose ID begin with a certain value (`urn:ngsi-ld:Domain.*`) and a more complex idPattern to exclude 2 certain entities (`^(?!.*(urn:ngsi-ld:Domain:1|urn:ngsi-ld:Domain:2)).*$`).
