### ISSUE TITLE
Docker image 1.7.0 is still missing libtinyxml2.so.6

### ISSUE THREAD

**Issue by ibordach** [Fiware/context.Orion-LD#1699]
Last Image working: 1.7.0-PRE-1637
Any newer Image failed with  

 `orionld: error while loading shared libraries: libtinyxml2.so.6: cannot open shared object file: No such file or directory`

**Comment by kzangeli** [comment]
Uy, that's not good!
Thank you for reporting!

**Comment by ibordach** [comment]
The new 1.7.0 is working. :-)

**Comment by kzangeli** [comment]
Yes!
Found and fixed the error yesterday night.
Forgot to inform you, but you were fast enough! :)

**Comment by kzangeli** [comment]
Fixed
