### ISSUE TITLE
ResourceNotFound Error (404) when using PUT or PATCH /entities/{entityId} but GET Request returns 200 OK for the same {entityId}

### ISSUE THREAD

**Issue by dimitriskranias** [Fiware/context.Orion-LD#1713]
Using Orion 1.6.0, I stumble into this error when I am trying to use Merge PATCH or Overwrite PUT.

I am creating an entity using POST /entities and I am able to GET /entities/{entityId} (part of the result below, cut a bit of the context and some of the attributes):
![εικόνα](https://github.com/user-attachments/assets/397dd495-8b95-4422-b7ca-8a3d01e8aa57)

When I am trying for example to use Overwrite PUT request (/entities/{entityId}) for the Entity described above, urn:i-STENTORE:Demo3Temp:Temp, I get the following error:
`{
    "type": "https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
    "title": "Service Not Found",
    "detail": "/ngsi-ld/v1/entities/urn:i-STENTORE:Demo3Temp:Temp"
}`
The body in my request is the following:
![εικόνα](https://github.com/user-attachments/assets/b6b7cd5b-e764-4d92-aaa2-b3af757c5b70)

I am also providing in all these requests the Context in a Link Header and the Accept Header (application/json for POST, PUT, PATCH and application/ld+json for GET)

Is there any obvious reason that this error keeps coming up? (As far as I've seen in the NGSI-LD Specification, it should appear "If the target Entity ID is not a valid URI or it is not present", but that doesn't make much sense, as it should happen in the GET request as well)

Thank you in advance

**Comment by dimitriskranias** [comment]
Just when I found that with adding the flag -experimental these two endpoints worked perfectly and was ready to close the Issue, I found that the POST /entities/{entityId}/attrs "breaks" with the following error (Error 502: Bad Gateway):
`{
    "message": "An invalid response was received from the upstream server",
    "request_id": "838d9876624446416e543127ab839504"
}`
Note that before adding the experimental flag it worked perfectly for the below payload (I was getting a 207 response because I added "type" attribute to the payload):
`{
    "type": "HydroPlant",
    "category": {
        "type": "Property",
        "value": "Power Production"
    }
}`
Every other request of the Entities, Entity Operations and Entity Discovery APIs works fine in both situations (with and without the experimental flag). Just these 3 (the 2 in my previous message and this one) seem to be not working consistently.

**Comment by kzangeli** [comment]
So, not sure what happened here. The error you've seen is not from the broker itself.
It could of courser be because of something the broker sent.

Now, first, please avoid using the service `POST /entities/{entityId}/attrs`.
It's old, bad and about to be deprecated.
Use instead `PATCH /entities/{entityId}`.  It does everything and more, and it is a true PATCH.
I know there is a bug or two for that API endpoint and I simply prefer not to spend time on it as it is "old code".

So, please try to use the newer and better PATCH Entity and let me know.

**Comment by dimitriskranias** [comment]
> Now, first, please avoid using the service `POST /entities/{entityId}/attrs`. It's old, bad and about to be deprecated. Use instead `PATCH /entities/{entityId}`. It does everything and more, and it is a true PATCH. I know there is a bug or two for that API endpoint and I simply prefer not to spend time on it as it is "old code".

Thank you, that is very useful to know. Does the same apply to `PATCH /entities/{entityId}/attrs` (regarding the deprecation part), or this one is good to use?

> So, please try to use the newer and better PATCH Entity and let me know.

To clarify, the new PATCH /entities/{entityId} is the one when I have -experimental flag in my broker? I mean without the flag it doesn't work at all, but I wanted to be sure. 

Also is there any documentation/list about which NGSI-LD HTTP requests have been implemented in the legacy mongo driver and which in the new one (and which are probably in both)? The only one that I have found thus far is the release notes of version 1.2.0, where some of them are described to be updated to the new driver

**Comment by kzangeli** [comment]
> Thank you, that is very useful to know. Does the same apply to PATCH /entities/{entityId}/attrs (regarding the deprecation part), or this one is good to use?

Yes, I wouldn't use that one either.  The new PATCH (/entities/{entityId} does all you need except PUT.
And yes, you need the ' -experimental' flag on (almost sure :))

> Also is there any documentation/list about which NGSI-LD HTTP requests have been implemented in the legacy mongo driver and which in the new one (and which are probably in both)?

All but the two new PUT/PATCH /entities/{entityId} are implemented in both "modes" and without '-experimental' (or -mongocOnly) the old implementation will be used.
My recommendation is to use the new implementation.

**Comment by dimitriskranias** [comment]
Thank you very much for the clarifications, I am closing the issue
