### ISSUE TITLE
If no Accept header provided --> application/json content shall be provided

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#23]
The default content to be provided in the absence of an Accept header is `application/json`

**Comment by kzangeli** [comment]
I believe this is implementad already. Time ago.
If you have an example that fails, I'd love to see it :)

**Comment by jmcanterafonseca** [comment]
POST /ngsi-ld/v1/entities/

{
"id": "urn:ngsi-ld:Vehicle:V233",
"type": "Vehicle"
}

GET /ngsi-ld/v1/entities/urn:ngsi-ld:Vehicle:V233 
(no headers, accept, etc.)
{
    "id": "urn:ngsi-ld:Vehicle:V233",
    "type": "Vehicle",
    "@context": "https://forge.etsi.org/gitlab/NGSI-LD/NGSI-LD/raw/master/defaultContext/defaultContext.jsonld"
}

and Content-Type header incorrectly says

Content-Type →application/ld+json 

so this has not been fixed yet ...

**Comment by kzangeli** [comment]
Think I misunderstood.
What you are saying is that if a request is done without explicitly stating that it wants `application/ld+json`, the context must be returned as a HTTP header, and not in the payload and the mime type must be `application/json`.  OK, makes sense.

**Comment by kzangeli** [comment]
Actually, about what we talked about, this confusion with contexts ...
No context should be returned, nor in payload nor in HTTP header.
All items in the payload should use their real names - the long ones specified by the context that was used when creating the entity (no aliases).

We still need to discuss all the intrinsics about this and then change the orionld broker "completely" ...

**Comment by kzangeli** [comment]
Seems to be fixed now.
PR #58 proves it.

**Comment by jmcanterafonseca** [comment]
MIME type tests are working. closing
