### ISSUE TITLE
Enumerated attributes are not expanded/compacted

### ISSUE THREAD

**Issue by jason-fox** [Fiware/context.Orion-LD#236]
According to https://w3c.github.io/json-ld-syntax/#shortening-iris

> The vocabulary mapping can be used to shorten IRIs that may be vocabulary relative by removing the IRI prefix that matches the vocabulary mapping. This is done whenever an IRI is determined to be vocabulary relative, i.e., used as a property, or a value of @type, or as the value of a term described as "@type": "@vocab".

> Note that two IRIs were shortened, unnecessary arrays are removed, and simple string values are replaced with the string.

This is not implemented.

1.   In the *Building* model - `"category": {"type": "Property", "value": ["commercial"]},  should be returned as a string not an array when compacted

2. Where enumerated values are part of the context and @vocab has been set-up the *values* should be expanded

**Comment by jmcanterafonseca** [comment]
I cannot understand point 1., why?

Thanks

**Comment by jason-fox** [comment]
Given the following expanded document:

```json
[{
  "@id": "http://example.org/places#BrewEats",
  "@type": ["http://example.org/Restaurant"],
  "http://example.org/name": [{"@value": "Brew Eats"}]
}]
```

And the following context:

```json
{
  "@context": {
    "@vocab": "http://example.org/"
  }
}
```
The compaction algorithm will shorten all vocabulary-relative IRIs as shown:

```json
{
  "@context": {
    "@vocab": "http://example.org/"
  },
  "@id": "http://example.org/places#BrewEats",
  "@type": "Restaurant",
  "name": "Brew Eats"
}
```

See how `@type` is *no longer* an array in the response.

**Comment by jmcanterafonseca** [comment]
for the time being the NGSI-LD API does not allow multiple types i.e. type
cannot be an array, although there have been some discussions within ETSI
to extend it, but not everybody agrees in adding such a complexity ...

**Comment by kzangeli** [comment]
This is pretty confusing.
Is "@type" to be treated as "type"? 
And "@id" as "id" ?
[ The broker doesn't work that way ]

If not, "@type" is just any other attribute and can be of any type.
And, this not an entity, as both "id" and "type" are missing.
However, if it's a vector, it's a vector. Only way to change it to a string is by updating it.

To me it seems you are looking for functionality that the broker isn't even meant to do

**Comment by jmcanterafonseca** [comment]
in principle NGSI-LD defines its own encoding on top of JSON-LD, so not any
valid JSON-LD document is a valid NGSI-LD document, and a as a result, Ken
is right "@type", "@id" shall not be used by the developer

**Comment by jason-fox** [comment]
Superceded by Vocabulary Property - closing
