### ISSUE TITLE
One mongoDB collection per Entity Type

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#252]
Traditionally Orion has stored all Entities within a MongoDB collection, named `entities`. 

A better approach would be to store Entities in different collections, having a separate Collection per Entity Type. That would simplify considerably the management of DB content and the usage of tools to browse the DB.

**Comment by kzangeli** [comment]
This is true.
Right now, the orionld implementation makes a heavy use of mongoBackend, and the proposed change is just not possible.

However, we have future plans to move away from mongoBackend and implement a very much improved database layer, and when that work is started (actually there is already one or two operations that don't use mongoBackend - as a pilot test) it will be pretty easy to implement what @jmcanterafonseca is proposing. I imagine both queries and insertions should benefit from a change of this kind - from an efficiency point of view.
