### ISSUE TITLE
In timestamps trailing timezone `Z` has to be rendered always

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#26]
When rendering timestamp data, and as per the latest version of the spec the trailing timezone (always 'Z', has to be rendered). This applies for `observedAt, createdAt, modifiedAt` or any other `DateTime` attribute.

**Comment by jmcanterafonseca** [comment]
in addition DateTime shall always be represented in UTC.

**Comment by kzangeli** [comment]
This issue I believe I fixed a long time ago ...
Took a look in functests and all DateTime seems to end in 'Z'.
About UTC, the broker uses the syscall `time()` to obtain timestamps and `time()` returns UTC.

So, issue seems solved to me.

**Comment by jmcanterafonseca** [comment]
fixed. tests are working
