### ISSUE TITLE
When payload is an empty object append entity attributes shall return 400

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#29]
See

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextProvision/append_entity_attrs_test.js#L76

**Comment by kzangeli** [comment]
Right now, the broker responds like this:
```
HTTP/1.1 404 Not Found
Content-Length: 143
Content-Type: application/json
Date: Mon, 06 May 2019 10:05:47 GMT

{
  "type": "http://uri.etsi.org/ngsi-ld/errors/BadRequestData",
  "title": "Entity does not exist",
  "details": "urn:ngsi-ld:doesnotexist"
}
```

It's not a bad response.

It is also not a bad response to complain about the empty payload.
It's all about the order in which the errors are detected.
If you think that the empty payload should be detected before the non-existing entity, I have no problem with that. 
But, I would implement this check in one place only, for all possible requests.
If a payload comes in empty, the broker will return a 400 Bad Request whatever the URI PATH is.

Is that OK?

**Comment by kzangeli** [comment]
I implemented the check for "{}" (the resulting tree after parsing is a single object of type "Object" and with out children) and this is the new response:
```
HTTP/1.1 400 Bad Request
Content-Length: 113
Content-Type: application/json
Date: Mon, 06 May 2019 10:26:19 GMT

{
  "type": "http://uri.etsi.org/ngsi-ld/errors/InvalidRequest",
  "title": "Empty Payload",
  "details": "{}"
}
```

Better like that?

**Comment by jmcanterafonseca** [comment]
Yes, I think an empty payload is an error that should come before, as it has to do with the content of the request, which is totally incorrect. I also agree that this should be unified for any request.

**Comment by kzangeli** [comment]
Good. Thanks. PR coming soon to a theater near you :)

**Comment by jmcanterafonseca** [comment]
@kzangeli what happens if the content of the payload is `""`? We need to check that case as well. Also if the content of the payload is `null` or nothing inside ... (empty byte stream).

**Comment by kzangeli** [comment]
NULL is already taken care of. Empty I think also.
Will add more tests in the functest of this next PR

**Comment by jmcanterafonseca** [comment]
and `""` because `""` is also valid JSON but not semantically correct for our API ...

**Comment by kzangeli** [comment]
Fixed in https://github.com/FIWARE/context.Orion-LD/pull/53

**Comment by MohamedSadiq102** [comment]
#Verified @jason-fox
