### ISSUE TITLE
array of object (URIs) is not supported for relationships

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#34]
See test at 

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextProvision/create_entity_test.js#L239

```
const entity = {
      'id': 'urn:ngsi-ld:T:' + new Date().getTime(),
      'type': 'T',
      'AR1': {
        'type': 'Relationship',
        'object': ['urn:ngsi-ld:T:1234', 'urn:ngsi-ld:T:5678']
      }
    };
```

**Comment by kzangeli** [comment]
This works just fine, see the funct4est of PR https://github.com/FIWARE/context.Orion-LD/pull/49

**Comment by jmcanterafonseca** [comment]
orion-LD is crashing ... with the example

**Comment by jmcanterafonseca** [comment]
tested against http://orion.lab.fiware.org:1027 and it worked
