### ISSUE TITLE
Point to the official ETSI Core @Context

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#35]
The official Core @context is at

http://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld

Please modify your code to point to it and remove the old forge.etsi.... 

Thanks

**Comment by kzangeli** [comment]
Done in commit 48b566a5bf:
https://github.com/FIWARE/context.Orion-LD/commit/48b566a5bf10c3334f6736002ef69e2712076804#diff-cedb75d87dc0132bb4fded06804dea10L42

**Comment by jmcanterafonseca** [comment]
sorry Ken, but we need to update to HTTPs

https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld

**Comment by kzangeli** [comment]
Uff .. that's gonna cost me a lot of time ...
No probs. They pay me to do this kind of things too :)
I imagine the content of https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld must also change all http to https ... ? And everyehere else

**Comment by jmcanterafonseca** [comment]
we will wait until we get confirmation from ETSI for the new abbreviated URI `https://uri.etsi.org/ngsi-ld/v1` (no trailing '/', by the way).

**Comment by jmcanterafonseca** [comment]
as ETSI did not provide any feedback about the redirection we will stick with

 https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld  

so closing this issue.
