### ISSUE TITLE
Geometry type "LineString" is not properly processed

### ISSUE THREAD

**Issue by michaeI-s** [Fiware/context.Orion-LD#392]
Hi,

I'm trying to create an entity with a `LineString` GeoProperty with the following request:
```curl
curl --location --request POST 'http://<SERVER_IP>:<PORT>/ngsi-ld/v1/entities' \
--header 'Content-Type: application/ld+json' 
--data-raw '{
    "id": "urn:ngsi-ld:GtfsShape:900000470000-900000445316:MS",
    "type": "GtfsShape",
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "LineString",
            "coordinates": [
                [
                    14.32517,
                    51.75037
                ],
                [
                    14.59893,
                    51.61409
                ]
            ]
        },
        "observedAt": "2020-03-02T16:31:13.124Z"
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

According to the response (201 Created) it was successfully created. But when trying to GET it via `/entities?type=GtfsShape`, nothing is returned.<br>
I also noticed that the POST response body contains a single comma (',') instead of an empty body and this seems quite unusual. I assume there could be a server-side parsing issue?

Whereas when trying to create an entity with the geometry type `Point`, it can be queried (although POST response body still contains that comma):

```json
curl --location --request POST 'http://<SERVER_IP>:<PORT>/ngsi-ld/v1/entities' \
--header 'Content-Type: application/ld+json' 
--data-raw '{
    "id": "urn:ngsi-ld:GtfsShape:900000470000-900000445316:MS",
    "type": "GtfsShape",
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                14.32517,
                51.75037
            ]
        },
        "observedAt": "2020-03-02T16:31:13.124Z"
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

I'm using the following Orion-LD version:
```json
{
  "Orion-LD version": "post-v0.1.0",
  "based on orion": "1.15.0-next",
  "kbase version": "0.3",
  "kalloc version": "0.3",
  "khash version": "0.3",
  "kjson version": "0.3",
  "boost version": "1_62",
  "microhttpd version": "0.9.48-0",
  "openssl version": "OpenSSL 1.1.0l  10 Sep 2019",
  "mongo version": "1.1.3",
  "rapidjson version": "1.0.2",
  "libcurl version": "7.52.1",
  "libuuid version": "UNKNOWN",
  "branch": "(HEAD",
  "Next File Descriptor": 18
}
```

Kind regards,
Michael

**Comment by kzangeli** [comment]
Thanks for reporting!

I made a quick test and it seems that the entity isn't created.
The broker says OK, all good, but no entity is created.

Geolocation is still a pretty green area in Orion-LD.
Very little time has been spent on it so far, just enough to make "a few things work".
It's high on my ToDo list but I guess it's time to move it even higher.
Starting with this issue.

**Comment by michaeI-s** [comment]
Hi Ken,

great! Good to hear about your priority shifting.
May the force of the 36h day be with you. ;)

Thanks and kind regards,
Michael

**Comment by kzangeli** [comment]
So, I actually found a way ...
Test it, see if it works.
LineString wasn't implemented. Only Point and Polygon.
At least, now the entity is created.
But if the entire geolocation thing works you will have to tell me.
I don't know how to test it :(

**Comment by michaeI-s** [comment]
Thanks Ken for fixing!

As of the latest version

```json
{
  "Orion-LD version": "post-v0.1.0",
  "based on orion": "1.15.0-next",
  "kbase version": "0.3",
  "kalloc version": "0.3",
  "khash version": "0.3",
  "kjson version": "0.3",
  "boost version": "1_62",
  "microhttpd version": "0.9.48-0",
  "openssl version": "OpenSSL 1.1.0l  10 Sep 2019",
  "mongo version": "1.1.3",
  "rapidjson version": "1.0.2",
  "libcurl version": "7.52.1",
  "libuuid version": "UNKNOWN",
  "branch": "(HEAD",
  "Next File Descriptor": 18
}
```
`LineString` is now a supported GeoJSON type in Orion-LD (besides `Point`and `Polygon`). :)
