### ISSUE TITLE
Multiple entities with same ID in /entityOperations/upsert payload returns "Bad Request"

### ISSUE THREAD

**Issue by michaeI-s** [Fiware/context.Orion-LD#463]
Hi,

when providing more than one entity with the same Id in the payload of a `/entityOperations/upsert` request, the error array of the multi status response contains an entry for each affected entity Id.

For example a response could look like this:
<pre>
{
    "@context": "https://fiware.github.io/data-models/context.jsonld",
    "success": [
        "urn:ngsi-ld:WeatherObserved:BME280:11448",
        "urn:ngsi-ld:WeatherObserved:BME280:7297",
        "urn:ngsi-ld:WeatherObserved:BME280:18533",
        "<b>urn:ngsi-ld:WeatherObserved:BME280:13782</b>",
        "urn:ngsi-ld:WeatherObserved:BME280:20494",
        "urn:ngsi-ld:WeatherObserved:BME280:9899",
        "urn:ngsi-ld:WeatherObserved:BME280:22025",
        "urn:ngsi-ld:WeatherObserved:BME280:24104",
        "urn:ngsi-ld:WeatherObserved:BME280:15836",
        "urn:ngsi-ld:WeatherObserved:BME280:10478",
        "<b>urn:ngsi-ld:WeatherObserved:BME280:13782</b>",
        "urn:ngsi-ld:WeatherObserved:BME280:3170",
        "urn:ngsi-ld:WeatherObserved:BME280:12358"
    ],
    "errors": [
        {
            "entityId": "<b>urn:ngsi-ld:WeatherObserved:BME280:13782</b>",
            "error": {
                "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
                "title": "",
                "detail": "Bad Request",
                "status": 400
            }
        }
    ]
}
</pre>

The error entry contains a `Bad Request 400` status and a non-descriptive empty `title` value.

However, multiple changes of sensor values in a given time period are not very uncommon, so this should not result in error messages. 
Instead, it seems reasonable to simply consider the entity with the most recently updated attribute values (those with the most recent timestamps) and ignore the others. For historical data all values should of course be processed.

Best regards,
Michael

**Comment by kzangeli** [comment]
This one is temporarily fixed - by picking just the last instance of an entity in the array - ignoring the rest.
In ETSI we're deciding how to treat this case and once decided and published, will be implemented
