### ISSUE TITLE
Missing type attribute in batch update causes context broker crash.

### ISSUE THREAD

**Issue by jason-fox** [Fiware/context.Orion-LD#503]
If I run the following batch update (where the first entry is missing a `type`:

```console
curl -L -X POST 'http://localhost:1026/ngsi-ld/v1/entityOperations/update' \
-H 'Content-Type: application/json' \
-H 'Link: <http://context-provider:3000/data-models/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '[
    {
      "id": "urn:ngsi-ld:TemperatureSensor:003",
      "category": null
    },
     {
      "id": "urn:ngsi-ld:TemperatureSensor:004",
      "type": "TemperatureSensor",
      "category": null,
      "temperature": null
    }
]'
```

The context broker exits rather than returning with a **400 Bad Request**

```
"git_hash": "db891a72a531ef4cc037caed5b04f8fe71da6814",
"compile_time": "Thu Jul 30 13:13:23 UTC 2020"
```

**Comment by jason-fox** [comment]
The `@context` used in the example can be found [here](https://raw.githubusercontent.com/FIWARE/tutorials.NGSI-LD/master/app/public/data-models/ngsi-context.jsonld)

**Comment by kzangeli** [comment]
The issue about missing entity type crashing the broker is fixed.
Note that an attribute value of `null` (which is used for deletion of attribute in some NGSI-LD requests) is not implemented yet in Orion-LD)

**Comment by jason-fox** [comment]
Fixed
