### ISSUE TITLE
PATCH with invalid payload causes broker to crash.

### ISSUE THREAD

**Issue by jason-fox** [Fiware/context.Orion-LD#504]
When sending a PATCH request with `Content-Type: application/json` but a plain text payload:

```console
curl -L -X PATCH 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:Product:001/attrs/price/value' \
-H 'Content-Type: application/json' \
-H 'Link: <http://context-provider:3000/data-models/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '89'
```

The expected **400 - Bad Request** does not occur. The context broker exits instead.

```
"git_hash": "db891a72a531ef4cc037caed5b04f8fe71da6814",
"compile_time": "Thu Jul 30 13:13:23 UTC 2020"
```

**Comment by jason-fox** [comment]
The `@context` used in the example can be found [here](https://raw.githubusercontent.com/FIWARE/tutorials.NGSI-LD/master/app/public/data-models/ngsi-context.jsonld)

**Comment by jason-fox** [comment]
Verified: eddd37530fb7cb748ad582b5c20ea4327accd558

**Comment by kzangeli** [comment]
The func-test implemented for this issue, test/functionalTest/cases/0000_ngsild/ngsild_issue_0504.test has been removed as the new smart-input-format makes the test obsolete.

**Comment by jason-fox** [comment]
Even if a new simplified format is added, a payload of `89` is still not a valid JSON-LD document and is unacceptable as input. Please re-add the test/functionalTest/cases/0000_ngsild/ngsild_issue_0504.test test case.

Even assuming the `Link` header is in use, to be a valid JSON-LD document, at a minimum this is required

```json
{"value": 89}
```
 
If the `Link` header is not in use `@context` must be found in the body. 

```json
{"value": 89, "@context": "path/to/my/context.jsonld"}
```

**Comment by kzangeli** [comment]
Yeah, we changed the whole thing, as unfortunately JSON-LD needs the input to be a compound.
I'm fixing this.

About "_If the Link header is not in use @context must be found in the body_" ...
Eehhh, no.   That's not how NGSi-LD works.

This is how it works:
  * If "application/ld+json" is the Content-Type, the @context must be in the payload body.
  * If "application/json",  the @context cannot be in the payload body.
      - the context *may* be in the Link header  (doesn't have to)
      - if not, the Core context is used

**Comment by kzangeli** [comment]
And, it is true that I can put the test back once I redo the check that the payload body is either an Array or an Object.
