### ISSUE TITLE
Websocket support for notifications?

### ISSUE THREAD

**Issue by hspaay** [Fiware/context.Orion-LD#551]
Hi, recently discovered FiWare and I'm reading up on lots of documentation. I have worked on an IoT standard before and am happy to see all the effort going into an open standard that is so encompassing. Great job!

I have a question on receiving of notifications. The docs don't go into how the notification is sent to the subscriber but from the subscription it looks like it needs an HTTP endpoint. I probably misunderstand this as it would make it impossible for web clients and clients behind a firewall to receive push notifications. While I've seen the mention of a GE Proxy, it seems a bit complicated to require that for all brokers. Might as well built it in?

Am I missing something or is this the way it is intended to be used?
Thanks

**Comment by kzangeli** [comment]
Hello there.
First of all, questions like this don't really fit as an issue on github. We use stackoverflow for this kind of things. Look for the tags 'fiware' and 'orion'.

That said, notifications via websockets is on the roadmap for 2021. 
Apart from HTTP, MQTT is also supported for notifications.

**Comment by hspaay** [comment]
Great, thank you for the quick reply. I will direct any further questions to Stackoverflow.
I'll look into MQTT. Thanks again
