### ISSUE TITLE
Is there an entitiy for Contect Broker attributes?

### ISSUE THREAD

**Issue by hspaay** [Fiware/context.Orion-LD#575]
Since the NGSI-LD spec will likely evolve (after all we have had v1 and v2 already), is there a way to determine what version a context broker supports?
Possibly an entity for the broker itself with attributes that describe its name, version etc... ?
Thank you kindly,

**Comment by kzangeli** [comment]
Yes, you are right. It would be useful for users to be able to query the broker about the version of NGSI-LD that is supported.
I have just the place for it:
```
GET /ngsi-ld/ex/v1/version
```
I could easily include this info right there.

However, this is not a request that is supported by the NGSI-LD standard. Only Orion-LD supports this service, no other NGSI-LD compliant broker.
I'll bring this to ETSI ISG CIM and we'll try to agree on a standardized way to provide this information.
Meanwhile I'll add it to my "special" service.

In the future, questions like this one don't really belong in the github repo. Bugs do, questions don't.
Stackoverflow is the place - the question will have more visibility there.

**Comment by hspaay** [comment]
Ah yes, that is great.
Thank you for bringing this to ESTI ISG CIM. Maybe good to consider other attributes such as uptime and load, for server monitoring, although arguably that could be considered out of scope. (kinda like the MQTT $SYS topic).
Thanks again and I'll try to remember to direct these kind of questions to Stackoverflow
