### ISSUE TITLE
Temporal DB Tables

### ISSUE THREAD

**Issue by kzangeli** [Fiware/context.Orion-LD#606]
```
CREATE DATABASE xxx;

CREATE EXTENSION IF NOT EXISTS plpqsql;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TYPE ValueType AS ENUM
(
  'String',
  'Number',
  'Boolean',
  'Relationship',
  'Compound',
  'DateTime',
  'GeoPoint',
  'GeoPolygon',
  'GeoLineString',
  'GeoMultiPolygon',
  'GeoMultiLineString',
  'LanguageMap'
);

CREATE TYPE OperationMode AS ENUM
(
  'Create',
  'Append',
  'Update',
  'Replace',
  'Delete'
);

CREATE TABLE entities
(
  instanceId   TEXT PRIMARY KEY,
  ts           TIMESTAMP NOT NULL,
  opMode       OperationMode,
  id           TEXT NOT NULL,
  type         TEXT NOT NULL
);

CREATE TABLE attributes IF NOT EXISTS
(
  instanceId          TEXT PRIMARY KEY,
  opMode              OperationMode,
  id                  TEXT NOT NULL,
  entityId            TEXT NOT NULL,
  observedAt          TIMESTAMP,
  valueType           ValueType,
  subProperty         BOOL,
  unitCode            TEXT,
  datasetId           TEXT,
  text                TEXT,
  boolean             BOOL,
  number              FLOAT8,
  datetime            TIMESTAMP,
  geoPoint            GEOGRAPHY(POINTZ, 4326),
  geoPolygon          GEOGRAPHY(POLYGON, 4326),
  geoMultiPolygon     GEOGRAPHY(MULTIPOLYGON, 4326),
  geoLineString       GEOGRAPHY(LINESTRING, 4326),
  geoMultiLineString  GEOGRAPHY(MULTILINESTRING, 4326),
  ts                  TIMESTAMP NOT NULL
);

CREATE TABLE subAttributes
(
  instanceId          TEXT PRIMARY KEY,
  id                  TEXT NOT NULL,
  entityId            TEXT NOT NULL,
  attrInstanceId      TEXT NOT NULL,
  observedAt          TIMESTAMP,
  unitCode            TEXT,
  valueType           ValueType,
  text                TEXT,
  boolean             BOOL,
  number              FLOAT8,
  datetime            TIMESTAMP,
  geoPoint            GEOGRAPHY(POINTZ, 4326),
  geoPolygon          GEOGRAPHY(POLYGON, 4326),
  geoMultiPolygon     GEOGRAPHY(MULTIPOLYGON, 4326),
  geoLineString       GEOGRAPHY(LINESTRING, 4326),
  geoMultiLineString  GEOGRAPHY(MULTILINESTRING, 4326),
  ts                  TIMESTAMP NOT NULL
);
```

A graphical representation can be found here:
[DB Diagram](https://dbdiagram.io/d/5fff0f1f80d742080a362f3c)

For the current implementation, we decided to stay with the table structure and declare the 3 tables to be timescale hypertables and therefore get its improved handling of timeseries.

All text fields, except the "text"-field will be changed to varchar, for lower memory consumption and improved performance.
Additional indices over ts&id(&entityId)(&attributeId) will be evaluated. 

The decision was made, that future changes into a more relational structure will not be done before carefully evaluating the current schema.

Documentation needs to be extended with the required permissions for a db-user(e.g. create schema, enable extensions)

**Comment by wistefan** [comment]
A graphical representation can be found here:

**Comment by wistefan** [comment]
SRIDs should be changed:

CREATE DATABASE xxx;

CREATE EXTENSION IF NOT EXISTS plpqsql;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TYPE ValueType AS ENUM
(
  'String',
  'Number',
  'Boolean',
  'Relationship',
  'Compound',
  'DateTime',
  'GeoPoint',
  'GeoPolygon',
  'GeoLineString',
  'GeoMultiPolygon',
  'GeoMultiLineString',
  'LanguageMap'
);

CREATE TYPE OperationMode AS ENUM
(
  'Create',
  'Append',
  'Update',
  'Replace',
  'Delete'
);

CREATE TABLE entities
(
  instanceId   TEXT PRIMARY KEY,
  ts           TIMESTAMP NOT NULL,
  opMode       OperationMode,
  id           TEXT NOT NULL,
  type         TEXT NOT NULL
);

CREATE TABLE attributes IF NOT EXISTS
(
  instanceId          TEXT PRIMARY KEY,
  opMode              OperationMode,
  id                  TEXT NOT NULL,
  entityId            TEXT NOT NULL,
  observedAt          TIMESTAMP,
  valueType           ValueType,
  subProperty         BOOL,
  unitCode            TEXT,
  datasetId           TEXT,
  text                TEXT,
  boolean             BOOL,
  number              FLOAT8,
  datetime            TIMESTAMP,
  geoPoint            GEOGRAPHY(POINTZ, 4326),
  geoPolygon          GEOGRAPHY(POLYGON, 4267),
  geoMultiPolygon     GEOGRAPHY(MULTIPOLYGON, 4267),
  geoLineString       GEOGRAPHY(LINESTRING),
  geoMultiLineString  GEOGRAPHY(MULTILINESTRING),
  ts                  TIMESTAMP NOT NULL
);

CREATE TABLE subAttributes
(
  instanceId          TEXT PRIMARY KEY,
  id                  TEXT NOT NULL,
  entityId            TEXT NOT NULL,
  attributeId         TEXT NOT NULL,
  observedAt          TIMESTAMP,
  unitCode            TEXT,
  valueType           ValueType,
  text                TEXT,
  boolean             BOOL,
  number              FLOAT8,
  datetime            TIMESTAMP,
  geoPoint            GEOGRAPHY(POINTZ, 4326),
  geoPolygon          GEOGRAPHY(POLYGON, 4326),
  geoMultiPolygon     GEOGRAPHY(MULTIPOLYGON, 4326),
  geoLineString       GEOGRAPHY(LINESTRING, 4326),
  geoMultiLineString  GEOGRAPHY(MULTILINESTRING, 4326),
  ts                  TIMESTAMP NOT NULL
);

**Comment by kzangeli** [comment]
Not needed anymore - the DB is described in markdown docs, reachable via top level README.md
