### ISSUE TITLE
Delete Entity returns HTTP status code 200 instead of 204

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#7]

**Comment by jmcanterafonseca** [comment]
https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextProvision/delete_entity_test.js

**Comment by kzangeli** [comment]
Fixed in https://github.com/Fiware/context.Orion-LD/commit/18a79439ac6f1e9e9a8788d44fd9ea49de170bce

**Comment by jmcanterafonseca** [comment]
verified
