### ISSUE TITLE
Implementation planning for Temporal Evolution API

### ISSUE THREAD

**Issue by oolong-high** [Fiware/context.Orion-LD#744]
I'm trying to use the API to query Temporal Evolution of entities from an NGSI-LD system.

`GET /ngsi-ld/v1/temporal/entities # Not implemented in Alpha Release 1`

I've read in developer-documentation that it's not implemented yet.
Could you please inform me that you have a plan for when it will be implemented.

**Comment by kzangeli** [comment]
We have just pushed a first full version of the implementation of TRoE (temporal representation od entities) to the develop branch.
Tests about to start.
So, it's "there", only in a terribly green state still.
If you want to try it out, you are more than welcome to help us find bugs in this initial implementation.
For production usage of TRoE, I would recommend to wait a few months, at least, for the feature to be fully tested.

**Comment by oolong-high** [comment]
Thank you for getting back to me.
```
GET /ngsi-ld/v1/csourceSubscriptions # Not implemented in Alpha Release 1
GET /ngsi-ld/v1/temporal/entities # Not implemented in Alpha Release 1
```
Are these also pushed to the develop branch?
I would be very happy if you could let me know the target code file from you as I cannot find it.

**Comment by kzangeli** [comment]
target code file ... would a docker image do?
https://hub.docker.com/r/fiware/orion-ld/tags?page=1&ordering=last_updated

Registration Subscriptions (csourceSubscriptions) are not implemented. There's not even any plans to implement it any time soon.

Temporal Representation of Entities, as I explained earlier is on its way.
Retrieval and Query of temporal entities are done via a separate executable, namely Mintaka.
Orion-LD populates the historical database, while Mintaka takes care of the querying part.

**Comment by oolong-high** [comment]
Thanks for your replying.I understood that Registration Subscriptions (csourceSubscriptions) has not been implemented and is not planned to be implemented.

I was also made aware that troe queries are handled by Mintaka.
https://github.com/Trigyn-Technologies/Mintaka

**Comment by wistefan** [comment]
@oolong-high You are refering to the wrong project for mintaka, the one you mentioned is outdated. Please use this one: https://github.com/FIWARE/mintaka

**Comment by oolong-high** [comment]
Thank you for pointing out. You're right.
