### ISSUE TITLE
Docker-compose: Startup Error (cannot connect to mongo - doing 100 retries with a 1000 microsecond interval)

### ISSUE THREAD

**Issue by tanktoo** [Fiware/context.Orion-LD#75]
Hi,
I just updated the docker container. Now broker is not starting due to some connection problems to mongo db.
`time=Wednesday 15 May 08:30:35 2019.273Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[152]:mongoConnect | msg=Database Startup Error (cannot connect to mongo - doing 100 retries with a 1000 microsecond interval)`
As far as I can see the mongo db is running. Maybe there is something wrong with the new docker image? System is started via docker-compose.

**Comment by kzangeli** [comment]
We're experimenting with docker right now, trying to get functional tests running at PR creation.
It has proved more difficult than expected. Hopefully the problem will be fixed today.
The problem you are seeing might be due to this.
Can you go back to the older docker image until the problem is solved?

**Comment by tanktoo** [comment]
No hurry, will do something else. Was just wondering. Good luck with fixing :)

**Comment by caa06d9c** [comment]
The latest image was updated, you can try to pull changes.
To verify that image is correct, orion should return (/version) git hash : 21b88fe95a17feb29777b34f672d527ea92f692b

**Comment by tanktoo** [comment]
Seems to be fixed. Thanks

**Comment by MasaGon** [comment]
I got reproduced on latest docker image.

fiware/orion-ld            latest              ffab7da30589        2 hours ago         110MB

**Comment by caa06d9c** [comment]
Hi! Thank you for the report. Issue fixed in the latest commit, a new image will be available in ~15 min

**Comment by MasaGon** [comment]
Thanks! But I got another errors. Should I post as a different issue? (Booted with brand new mongo container)

```
orion_1  | time=Tuesday 21 May 02:40:41 2019.351Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionldRequestSend.cpp[183]:orionldRequestSend | msg=curl_easy_perform error 77
orion_1  | time=Tuesday 21 May 02:40:41 2019.351Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionldContextDownloadAndParse.cpp[118]:orionldContextDownloadAndParse | msg=orionldRequestSend failed (try number 1 out of 5): https://forge.etsi.org/gitlab/NGSI-LD/NGSI-LD/raw/master/defaultContext/defaultContext.jsonld
```

**Comment by caa06d9c** [comment]
Hi! No, we are investigating the reason.
