### ISSUE TITLE
When providing content which is not JSON nor JSON-LD HTTP status code shall be 415 and not 400

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#8]
(spec has to be updated)

**Comment by jmcanterafonseca** [comment]
https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextProvision/protocol_errors_test.js

**Comment by kzangeli** [comment]
Fixed in https://github.com/Fiware/context.Orion-LD/commit/2e12e41f0a924115b3d17cbb6df69492e7dc20fd

**Comment by jmcanterafonseca** [comment]
verified
