### ISSUE TITLE
Orion-LD notifications.

### ISSUE THREAD

**Issue by jandres6579** [Fiware/context.Orion-LD#808]
Hi:

After I create an entity and subscribe by type, if I run a patch request over one of its properties but with the current value, the notification arrives. 

Is it correct or a bug? 

If It is a bug and you can't simulate it, can you send post (entity, subscription) and patch(entity) example requests to compare with mine ones?

Thank you so much.

**Comment by kzangeli** [comment]
This is a "new feature" I implemented just a few days ago.
The old behaviour was to not notify on "same update", but this is a problem for some clients and the "quick fix" was to remove this check and "notify even if no change was made". Actually, the modifiedAt of the property changes, so there is really a change in the property even if its value hasn't changed.

That said, we're working on more fine tuning of notifications in ETSI ISG CIM (where the NGSI-LD API is defined), where one of the options will be "Don't notify if the property value isn't modified", so, eventually, the old behaviour will be possible again.
Other features will be "notify on deletion of entities", etc, etc.

But no it's not a bug, but a necessary change that may not be perfect for everybody.

**Comment by jandres6579** [comment]
Ok, thank you so much. Only to apport anything seems there are two kinds of clients, on a hand need all updates and another hand only updates.

In my opinion, notifications are only to inform about updates and if I'm not wrong now "modifiedAt" can't be obtained in the notification body. 

In this sense,  to avoid these kinds of notifications we had to use an auxiliary property and subscribe only to this attribute, and notificate about the rest of entity attributes.

In my opinion, if you want to receive every update, you can create for instance a timestamp attribute and change it when you want, and notificate about the rest of the attributes. No changes in orion-ld code and no conflict with notification essence.

I don't know another broker NGSI, NGSI-LD with this compartment regarding the notifications. Anyway now, there is not a problem for us, we solved it, the future nobody knows. 

I asked about it to know if we need to have in our mind this scenario or not.

Another solution may be broker subscriptions are configurable in this aspect.

Again, thank you so much for your soon answer. :)

**Comment by kzangeli** [comment]
Yes, this will be configurable. Will take a few months to get decided in ETSI and then implemented.
Sorry about this and happy you found a workaround!
