### ISSUE TITLE
Improve insert performance of temporal HTTP POST interface with multiple-row inserts

### ISSUE THREAD

**Issue by joriwinderickx-fm** [Fiware/context.Orion-LD#821]
Hello,

I am able to insert multiple instances of an attribute of an entity at the same time using the temporal interface of Orion. And, it is working nicely, though, I can send more data than Orion-LD and timescale can handle. It results in a buildup of latency to update the database with the latest temporal values. While looking through the source code, I noticed that each instance is inserted separately. I think the multiple instances of an attribute in e.g. an HTTP POST on the temporal interface leans perfectly to the ability to insert multiple values at the same time. It can improve insertion performance with a factor of +10x using the temporal interface depending on the size of the batch in the SQL query.

The Payload Body for "POST /temporal/entities" looks like this (based on doc in source code):
//
// {
//   "@context": "https://...",
//   "id": "urn:ngsi-ld:entities:E1",
//   "type": "T",
//   "attr1": [
//     {
//       "type": "Property",
//       "value": 14,
//       "observedAt": "2021-04-20T08:31:00Z",
//       ...
//     },
//     {
//       ...
//     },
//     ...
//   ],
//   "attr2": [
//     {
//       "type": "Relationship",
//       "object": "urn:xxx",
//       "observedAt": "2021-04-20T08:31:00Z",
//        ...
//     },
//     {
//       ...
//     }
//   ]
// }

Example row by row insertion (current implementation):
> INSERT INTO rates(rate_code, description) VALUES (1, 'standard rate');
> INSERT INTO rates(rate_code, description) VALUES (2, 'JFK');
...

Example multiple row insertion:
> INSERT INTO rates(rate_code, description) VALUES
(1, 'standard rate'),
(2, 'JFK'),
(3, 'Newark'),
(4, 'Nassau or Westchester'),
(5, 'negotiated fare'),
(6, 'group ride');

It is also a recommended practice from Timescale [source - 13-tips-to-improve-postgresql-insert-performance](https://blog.timescale.com/blog/13-tips-to-improve-postgresql-insert-performance/)

Thanks for the nice work and I hope you will consider this improvement.

**Comment by kzangeli** [comment]
Yes, I will definitely try something like this. And soon.
As I first implementation I just wanted it to work, and really didn't think performance would be an issue at this early stage ...
But, I was mistaken.
We're currently looking into how to rewrite the insertions.
Should be ready in a week or so.

Thank you for reporting!

**Comment by kzangeli** [comment]
Forgot to link to this issue when merging the PR that implements the "bulk" insertion.
This was implemented time ago, in PR #824
