### ISSUE TITLE
NGSI-LD subscription not working

### ISSUE THREAD

**Issue by diego-gv** [Fiware/context.Orion-LD#866]
Hello all,

I am trying to create a subscription to QuantumLeap to store the changes of NGSI-LD `AirQualityObserved` entities in CrateDB.

I create the subscription as follows:

```
curl --location --request POST 'http://0.0.0.0:1026/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'NGSILD-Tenant: openiot' \
--header 'fiware-servicepath: /' \
--data-raw '{
    "description": "Notify me any change in AirQualityObserver entities",
    "type": "Subscription",
    "entities": [
        {
            "type": "AirQualityObserved"
        }
    ],
    "notification": {
        "format": "keyValues",
        "endpoint": {
            "uri": "http://<local_ip>:5000",
            "accept": "application/json"
        }
    },
    "@context": "https://fiware.github.io/data-models/context.jsonld"
}'
```

The entities are as follows (with `keyValues` option):

```
{
    "@context": "https://fiware.github.io/data-models/context.jsonld",
    "id": "urn:ngsi-ld:AirQualityObserved:001",
    "type": "AirQualityObserved",
    "CO": 310.8633,
    "H2S": 4.31,
    "NO": 145.830002,
    "NO2": 37.040001,
    "O3": 28.1,
    "SO2": 6.69,
    "VOC": 9.034089,
    "location": {
        "type": "Point",
        "coordinates": [
            -1.220028,
            37.96825
        ]
    }
}
```

When an update is made, for example, to the `CO` parameter, no notification is sent. I have tried to configure the notification both to the QuantumLeap and to an open port through NetCat, but in no case, I get a notification.

I have created the same entity and subscription in NGSIv2 (saving the differences) and I do receive the notifications.

Best regards,

**Comment by kzangeli** [comment]
ok, I will take a look. Very simple example, should work.

Meanwhile, make sure your entities are on the right tenant.
And that the context `"https://fiware.github.io/data-models/context.jsonld` is used during the updates.
In general, it's a good idea to add complete curl commands and not just "descriptions" on what has been done.

**Comment by kzangeli** [comment]
"When an update is made" ... what's the exact update done?

**Comment by diego-gv** [comment]
I make the following request:

```
curl --location --request PATCH 'http://0.0.0.0:1026/ngsi-ld/v1/entities/urn:ngsi-ld:AirQualityObserved:001/attrs/CO' \
--header 'Content-Type: application/json' \
--data-raw '{
    "value": 310.8633
}'
```

On re-obtaining the NGSI-LD entity, the entity is up to date but has not issued a notification.

Regards,

**Comment by kzangeli** [comment]
ok, what about the tenant ?
The subscription lives on the tenant openiot.
Is that missing from your curl-statement?
The @context seems to be missing as well ...

The devil is in the details.
Try to paste in the **exact** curl statement that you issue when observing the malfunction.
_[ Cause like that, I can try to reproduce it. Or tell you what's wrong with the statement ]_

**Comment by diego-gv** [comment]
Very well, here is the complete and identical process that I obtain directly.

I create the entity:
```
curl --location --request POST 'http://0.0.0.0:1026/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "urn:ngsi-ld:AirQualityObserved:001",
    "type": "AirQualityObserved",
    "CO": {
        "type": "Property",
        "value": 313.7300109,
        "description": {
            "type": "Property",
            "value": "CO value"
        },
        "unitCode": "GQ",
        "dateObserved": {
            "type": "Property",
            "value": "2021-02-12T09:55:39.00Z"
        }
    },
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -1.220028,
                37.9682502
            ]
        }
    },
    "@context": [
        "https://fiware.github.io/data-models/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```
I create the subscription:
```
curl --location --request POST 'http://0.0.0.0:1026/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/ld+json' \
--header 'NGSILD-Tenant: openiot' \
--header 'fiware-servicepath: /' \
--data-raw '{
    "description": "Notify me any change in AirQualityObserver entities",
    "type": "Subscription",
    "entities": [
        {
            "type": "AirQualityObserved"
        }
    ],
    "notification": {
        "attributes": [
            "CO",
            "location"
        ],
        "format": "keyValues",
        "endpoint": {
            "uri": "http://192.168.18.123:5000",
            "accept": "application/json"
        }
    },
    "@context": "https://fiware.github.io/data-models/context.jsonld"
}'
```

I open port 5000 with NetCap (`nc -l -p 5000 -k`) and update the entity.

```
curl --location --request PATCH 'http://0.0.0.0:1026/ngsi-ld/v1/entities/urn:ngsi-ld:AirQualityObserved:001/attrs/CO' \
--header 'Content-Type: application/json' \
--data-raw '{
    "value": 311.8435
}'
```

The use of `NGSILD-Tenant` and `fiware-servicepath` is ambiguous in NGSI-LD (or at least I have not found the appropriate documentation), so I have used the requests I have found in the documentation. Also, the `fiware-service` header seems to be defunct, which is confusing and it is not clear when each header is needed.

Regards,

**Comment by kzangeli** [comment]
So, first about tenants and service path:

NGSI-LD (and Orion-LD) supports tenants (they were called services in NGSIv2).
The HTTP header to use in NGSI-LD is `NGSILD-Tenant`, but Orion-LD also supports `FIWARE-Service`, for backwards compatibility with Orion/NGSIv2.

The Service-Path is on its way into the NGSI-LD spec but not quite there yet.
As it was unclear that it would ever be part of the NGSI-LD API, Orion-LD ignores it.
Orion-LD sets it to "/" whatever you ask for - this is also for backwards compatibility somehow (an NGSIv2 entity must have a Service Path).

Now, back to the problem, your subscription lives in the tenant openiot, while the entity "urn:ngsi-ld:AirQualityObserved:001" lives in the default tenant.
These are two different "systems". You will never ever get a notification, triggered by a subscription in tenant A, about entities on tenant B.

So, try removing  `--header 'NGSILD-Tenant: openiot'` when creating the subscription, and you'll have both the entity and the subscription in the same tenant.
That way you have a chance to get notifications.

[ And, as I explained, the `fiware-servicepath` header serves for nothing in NGSI-LD right now - you can remove that as well ]

**Comment by diego-gv** [comment]
Ok, I have solved it and I understand. 

Thanks
