### ISSUE TITLE
Do Orion-LD APIs support absolute IRIs for linked data?

### ISSUE THREAD

**Issue by ctc-enokida** [Fiware/context.Orion-LD#895]
Hi.

I did some tests to understand the Orion-LD APIs specifications.

But, depending on the API, some can use absolute IRIs and some can't.
Is this a bug? or shouldn't it be supported?
(Please let me know if I'm using it wrong...)

Thank you so much.

The following is a description of what we tested.
①GET /ngsi-ld/v1/entities
：Everything's fine.
②POST /ngsi-ld/v1/entities
：Invalid entity type name error
③POST /ngsi-ld/v1/entityOperations
：Everything's fine.
④POST /ngsi-ld/v1/subscriptions
：I can register. However, it is recognized as another type and the notification does not fly

**Comment by ctc-enokida** [comment]
①GET /ngsi-ld/v1/entities
`curl -v 'http://localhost:1026/ngsi-ld/v1/entities?type=http://XXXX/YYYY/json-context.jsonld%23Person'`

②POST /ngsi-ld/v1/entities
`curl -i 'http://localhost:1026/ngsi-ld/v1/entities' \
-X POST \
-H 'content-type: application/json' \
-d '
{
    "id": "urn:ngsi-ld:Person:0001",
    "type": "http://XXXX/YYYY/ngsi-context.jsonld#Person",
    "name": {
        "type": "Property",
        "value": "test0001"
    }
}'`
Execution result
`{"type":"https://uri.etsi.org/ngsi-ld/errors/BadRequestData","title":"Invalid entity type name","detail":"http://XXXX/YYYY/ngsi-context.jsonld#Person"}`
③POST /ngsi-ld/v1/entityOperations
`curl -v -X POST 'http://localhost:1026/ngsi-ld/v1/entityOperations/create' \
-H 'x-kddi-api-key: orion-key-01' \
-H 'content-type: application/json' \
--data-raw '[
    {
        "id": "urn:ngsi-ld:Person:0001",
        "type": "http://XXXX/YYYY/ngsi-context.jsonld#Person",
        "name": {
        "type": "Property",
        "value": "test0001"
    }
},
    {
        "id": "urn:ngsi-ld:Person:0002",
        "type": "http://XXXX/YYYY/ngsi-context.jsonld#Person",
        "name": {
        "type": "Property",
        "value": "test0002"
    }
]'`
④POST /ngsi-ld/v1/subscriptions
`curl -i 'http://localhost:1026/ngsi-ld/v1/subscriptions' \
-X POST \
-H 'content-type: application/json' \
-d '
    {
        "description": "test0001",
        "type": "Subscription",
        "entities": [{"type": "http://XXXX/YYYY/ngsi-context.jsonld#Person"}],
        "notification": {
        "format": "normalized",
        "endpoint": {
            "uri": "http://tutorial:3000/subscription/test0001",
            "accept": "application/json"
        }
    }
}'`
Registration Results
`[{"type":"http://XXXX/YYYY/json-context.jsonld#Store"}],"notification":{"format":"normalized","endpoint":{"uri":"http://tutorial:3000/subscription/test0001","accept":"application/json"}},"@context`

**Comment by kzangeli** [comment]
You are supposed to be able to use **expanded values** pretty much everywhere.
Not that anybody is ever doing it, but, the API supports it.

So, probably a bug in Orion-LD what you're seeing - about (I assume) the hash character in 'case 2 - entity creation'.
Will check it and fix it if necessary.

About the subscription (don't mix up subscriptions with registrations - two quite different concepts).
This might be something related, the already expanded string might be expanded again,  resulting in an entity type that will never match.
Again, will check and fix if necessary.

Meanwhile ... perhaps start using the @context and send shortnames instead of already expanded names?

**Comment by kzangeli** [comment]
Just implemented a test for "invalid entity type", with the following body:
```
{
  "id": "urn:ngsi-ld:Person:0001",
  "type": "http://XXXX/YYYY/ngsi-context.jsonld#Person",
  "name": {
    "type": "Property",
    "value": "test0001"
  }
}
```
That worked just fine (201 Created).
I also searched the source code for "Invalid entity type name" - didn't find anything.

Are you using an older version of the broker?
My guess is you are - please make sure (https://hub.docker.com/r/fiware/orion-ld).

**Comment by kzangeli** [comment]
Did a test also for the subscription - just a quick test to make sure the entity type is correctly stored in the database.
Also can't see any anomalies there ...

So, make sure you're using the newest version of Orion-LD, and try again.

Post again if something fails and we'll fix it !

[ If all works just fine, then please close the issue, with a comment ]

**Comment by ctc-enokida** [comment]
Thank you for your quick answer.
I will install the latest version and check it out.
 (I'm using Orion-LD tags:0.7.0 right now.)

I will probably not be able to start checking until later this week, so I will check back and let you know.

Thank you so much.

**Comment by ctc-enokida** [comment]
Hi ken!
I have tested it with the latest version(post-v0.8.1) of Orion-LD.
All APIs(①〜④) worked fine.

Thanks for your research and cooperation.
I will close the issue.
Thank you.
