### ISSUE TITLE
"/ngsi-ld/ex/v1/notify" - notification cycles a certain number of times

### ISSUE THREAD

**Issue by sekiguchi-yohei** [Fiware/context.Orion-LD#907]
Hi. 

※I commented on this on StackoverFlow, but I thought it would be more appropriate as a topic for an issue, so I'll ask.
https://stackoverflow.com/questions/68341414/is-context-broker-federation-possible-with-ngsi-ld

I tried "/ngsi-ld/ex/v1/notify" because what we want to achieve is mutual entity copying between brokers based on notifications. 
When I created subscriptions with "/ngsi-ld/ex/v1/notify" as the endpoint in multiple Orions (A and B) and created an entity in A, the notifications cycled a certain number of times.（"timesSent": 2196） 
When I did the same operation with "/op/notify" in V2, the notifications were made only once to each other (both A and B have "timesSent": 1).
Is it possible to get the same result with "/ngsi-ld/ex/v1/notify"?
Or are there plans to fix this in future implementations?

Thank you so much.

**Comment by kzangeli** [comment]
ok, I saw the comment in SOF, and I might now finally have understood what you're after ...

You have two subscriptions:
* Broker A subscribes on Broker B
* Broker B subscribes on Broker A, on the same entity (or set of entities - not important).

Then you create a matching entity in one of the brokers:
* and you get a notification in the other broker
* that then also creates the entity and notifies the first broker,
* which provokes a update in the first broker and notification for the second broker
* and so on ... until eternity.

Is this the issue?

**Comment by sekiguchi-yohei** [comment]
Thank you very much.

>and so on ... until eternity.

Yes, that's correct.
I was expecting the same behavior with "/ngsi-ld/ex/v1/notify", since the notification was not repeated even after the same operation with "/op/notify" in V2.

So, I made this inquiry.
>Is it possible to get the same result with "/ngsi-ld/ex/v1/notify"?
>Or are there plans to fix this in future implementations?

**Comment by kzangeli** [comment]
Orion works that way because attributes that have not changed their values are not considered for notifications, which is currently part of the NGSIv2 protocol.

NGSI-LD defines a different behaviour, always notifying.

We're about to add a flag to configure how this is to work, in ETSI ISG CIM, where the API is defined. It's still not in the spec bit I could probably implement something "off the record" some time next week.
Once defined in ETSI, the behaviour will most likely change though.
This would fix your problem.

**Comment by sekiguchi-yohei** [comment]
Thank you very much！
I am eagerly waiting for it to be implemented this week.

**Comment by kzangeli** [comment]
Once the PR #910 is merged, start the broker with the new CLI option  `-noNotifyFalseUpdate` and let me know

**Comment by kzangeli** [comment]
The PR is merged.
Remember, this fix is temporary.
The real solution is to add a field to the subscriptions.
That will come ... not sure when.

**Comment by sekiguchi-yohei** [comment]
Thank you very much！
I tried "-noNotifyFalseUpdate" and it worked as I imagined it would.
