### ISSUE TITLE
Certificate of smartdatamodels.org is no more valid

### ISSUE THREAD

**Issue by MandatInternational** [Fiware/context.Orion-LD#931]
Due to the expiration of IdentTrust DST Root CA X3 [https://www.zdnet.com/article/fortinet-shopify-others-report-issues-after-root-ca-certificate-from-lets-encrypt-expires/](https://www.zdnet.com/article/fortinet-shopify-others-report-issues-after-root-ca-certificate-from-lets-encrypt-expires/) the certificate of smartdatamodels.org is no more valid inside the Orion-LD Docker container. Indeed the certificate issuer is no more recognized. It means that we cannot use `"@context": ["https://smartdatamodels.org/context.jsonld"]`

**Comment by MandatInternational** [comment]
![Capture d’écran 2021-10-01 160840](https://user-images.githubusercontent.com/17125975/135638351-ebf7e124-f920-47b0-8c63-af67411f4e7e.jpg)
![Capture d’écran 2021-10-01 160947](https://user-images.githubusercontent.com/17125975/135638352-ed269be8-4907-43bd-b570-2c7d6f9eadab.jpg)

**Comment by wistefan** [comment]
Hi,
thanks for mentioning that. I will create a docker image with the fix.

**Comment by wistefan** [comment]
The fix is available in the bug-fix release  fiware/orion-ld:0.8.2 
Please check if thats working for you and close the issue, if so.
Best,
Stefan

**Comment by MandatInternational** [comment]
It works now. Thank you very much for the quick action!
