### ISSUE TITLE
Subscriptions stringify data

### ISSUE THREAD

**Issue by JordiROP** [Fiware/context.Orion-LD#934]
Data sent to Cygnus-LD from Orion-LD are getting stringified when arriving to Cygnus-LD, Cygnus has te following parameter to maintain the original data type when inserting into a database.
     
     - "CYGNUS_POSTGRESQL_ATTR_NATIVE_TYPES=true" 

Is there any parameter to specify this in Orion-LD?

**Comment by kzangeli** [comment]
No parameter like that.
If you explain exactly what you're looking for, I might take it up in the ETSI standardization meetings of the NGSI-LD API.
