### ISSUE TITLE
Error while installing context.Orion-LD 

### ISSUE THREAD

**Issue by Anjali-NEC** [Fiware/context.Orion-LD#937]
I am trying to install context.Orion-LD from source. I am following below link to install context.Orion-LD on ubuntu 20.04.1:
https://github.com/FIWARE/context.Orion-LD/blob/develop/doc/manuals-ld/installation-guide-ubuntu-20.04.1.md

I am getting issue in compiling  the broker step: `make install` below is the screenshot for the same.

![orionld_log](https://user-images.githubusercontent.com/52558146/139222782-d3ba48b9-5d59-46f4-95b9-76f41977d143.PNG)

Please suggest how I can resolve this issue?

**Comment by kzangeli** [comment]
Hmm, there must be a new version of the compiler.
I will try myself and fix the problem.
The error is about sizes of char buffers and a more "picky" compiler :)

**Comment by kzangeli** [comment]
Reproduced the error (errors!) and fixing it.
I develop under Ubuntu 18.04 and using DEBUG compilation.
The error turns up in Ubuntu 20.04 and with RELEASE compilation.
That's why I wasn't aware about this problem.

Sorry ...

The fix should be ready before EOB.

**Comment by kzangeli** [comment]
Ah, and thanks for reporting!
Really appreciate it !

**Comment by kzangeli** [comment]
This PR should fix the problem: https://github.com/FIWARE/context.Orion-LD/pull/941
Please try again and close the issue if all is OK.

**Comment by kzangeli** [comment]
Six months have passed, no news.
Must assume all is good, closing the issue
