### ISSUE TITLE
Orion-LD tenant issue in multiple instance environment

### ISSUE THREAD

**Issue by yuskmr** [Fiware/context.Orion-LD#948]
In my environment, multiple OrionLD instances are running on a Kubernetes cluster. The environment consists of two OrionLD(0.8.0) instances, one MongoDB instance, and a LoadBalancer to OrionLD.
I created an entity with a new tenant by using "NGSILD-Tenant" header. Next, when I tried to retrieve it with "GET /entities", sometimes the retrieval succeeded, and sometimes it failed. The error message was below.

```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/NonExistingTenant",
    "title": "No such tenant",
    "detail": "Tenant01"
}
```
It seems that one OrionLD instance can recognize the new tenant, but the other cannot.

The original post for this issue is here.
https://stackoverflow.com/questions/70089932/orion-ld-tenant-issue-in-multiple-instance-environment

**Comment by kzangeli** [comment]
ok!
There it is! :)

I just solved it. I hope ...
This PR, that's still running: #947

**Comment by kzangeli** [comment]
PR #947 has been merged.
Please test and comment on the issue.
Close it if all is good.

**Comment by yuskmr** [comment]
I've tested and confirmed the issue is solved.
Thank for your quick response!
