### ISSUE TITLE
"LM error: Line too long" error while retrieving entity with long textual attribute value

### ISSUE THREAD

**Issue by PietroGreco** [Fiware/context.Orion-LD#954]
Hello,

Using OrionLD version "0.8.0" and "post-v0.8.1" we are encountering an issue with the retrieval of an entity having a textual attribute whose value is a very long string (base64 encoding of an image ... not a very good idea in this case, just an experiment).

We post the entity to the OrionLD without any issues (POST returns 201 Created and entity is correctly stored in mongo), however when we try to retrieve the entity through a query (by type or entity id), we get an "empty reply from server" error and the OrionLD crashes.

This is what the log says right before crashing:
```
fiware-orion | time=Tuesday 07 Dec 12:58:01 2021.541Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=CompoundValueNode.cpp[318]:add | msg=Adding String 'contentType', with value 'image/png' under '/' (toplevel)
fiware-orion | time=Tuesday 07 Dec 12:58:01 2021.541Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=CompoundValueNode.cpp[80]:CompoundValueNode | msg=Created TOPLEVEL compound node (a Object) at 0x7f3d10033b50

**** fiware-orion | CompoundValueNode.cpp[318]: **LM ERROR: LINE TOO LONG** ****

fiware-orion | time=Tuesday 07 Dec 12:58:01 2021.543Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=CompoundValueNode.cpp[80]:CompoundValueNode | msg=Created TOPLEVEL compound node (a Vector) at 0x7f3d100622e0
```

Here is the image that we encode in base64 (png, size 138.9KiB)
The resulting base64 string is 189584-char long
![closed_gripper](https://user-images.githubusercontent.com/50782151/145060015-1525098b-5c4c-46c8-86b4-469e9af73d67.png)

Thank you in advance

**Comment by kzangeli** [comment]
ok, that's interesting !
Never mind the "LM ERROR" . that's just debugging.
The crash on the other hand is very interesting.
Would you be able to start the broker under gdb, and post the stack dump after the crash?

**Comment by PietroGreco** [comment]
Hi Ken,

Thanks for your reply.

Yes, this is the stack dump after the crash (after issuing a query request to get all the entities of a specific type, and without subscribers to that type):
<pre>Thread 24 "MHD-connection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f0f4cb00700 (LWP 93)]
0x00005588848a0c44 in kjChildAdd ()
#0  0x00005588848a0c44 in kjChildAdd ()
#1  0x0000558884544268 in kjTreeFromCompoundValue(orion::CompoundValueNode*, KjNode*, bool, char**) ()
#2  0x0000558884542849 in kjTreeFromQueryContextResponse(bool, char*, bool, QueryContextResponse*) ()
#3  0x000055888452ca51 in orionldGetEntities(ConnectionInfo*) ()
#4  0x00005588845255ef in orionldMhdConnectionTreat(ConnectionInfo*) ()
#5  0x00005588844fe1c3 in ?? ()
#6  0x00005588847bdcdf in ?? ()
#7  0x00005588847bf288 in ?? ()
#8  0x00005588847c12b1 in ?? ()
#9  0x00005588847c41ee in ?? ()
#10 0x00007f0f56c2b4a4 in start_thread (arg=0x7f0f4cb00700)
    at pthread_create.c:456
#11 0x00007f0f52452d0f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97</pre>

In case of subscribers to that entity type this is what happens right after the POST, when OrionLD tries to send the notification:
<pre>Thread 22 "MHD-connection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f3171d74700 (LWP 73)]
0x0000000000880463 in kjChildAdd ()
#0  0x0000000000880463 in kjChildAdd ()
#1  0x0000000000544d96 in kjTreeFromCompoundValue(orion::CompoundValueNode*, KjNode*, bool, char**) ()
#2  0x000000000062a7c5 in kjTreeFromContextAttribute(ContextAttribute*, OrionldContext*, RenderFormat, char**) ()
#3  0x000000000062a361 in kjTreeFromNotification(NotifyContextRequest*, char const*, MimeType, RenderFormat, char**) ()
#4  0x00000000006202d8 in Notifier::buildSenderParams(NotifyContextRequest*, ngsiv2::HttpInfo const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RenderFormat, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) ()
#5  0x00000000006224e5 in Notifier::sendNotifyContextRequest(NotifyContextRequest*, ngsiv2::HttpInfo const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RenderFormat, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) ()
#6  0x0000000000736b3b in ?? ()
#7  0x00000000007468cb in processContextElement(ContextElement*, UpdateContextResponse*, ActionType, OrionldTenant*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ApiVersion, Ngsiv2Flavour) ()
#8  0x00000000006df106 in mongoUpdateContext(UpdateContextRequest*, UpdateContextResponse*, OrionldTenant*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, char const*, char const*, char const*, ApiVersion, Ngsiv2Flavour) ()
#9  0x0000000000529a5a in orionldPostEntities(ConnectionInfo*) ()
#10 0x00000000005271a7 in orionldMhdConnectionTreat(ConnectionInfo*) ()
#11 0x000000000050377d in ?? ()
#12 0x00000000007a9c7f in ?? ()
#13 0x00000000007abab8 in ?? ()
#14 0x00000000007ad66e in ?? ()
#15 0x00000000007b0d64 in ?? ()
#16 0x00007f317c74317a in start_thread () from /lib64/libpthread.so.0
#17 0x00007f3177cfcdc3 in clone () from /lib64/libc.so.6
</pre>

OrionLD version 0.8.0

Let me know if this is enough
Thanks again
Pietro

**Comment by kzangeli** [comment]
ok, that helps ... only, you have a broker without debugging symbols, so, we can't see exactly where it crashes.
Never mind. I have to reproduce the error in my own system in order to be able to fix it anyway.

I'm a little bit busy right now, but I'll do my best to look into this as soon as I can

**Comment by kzangeli** [comment]
So, finally ...
The crash has been fixed, but what you are trying to do will still not work as the maximum size of an attribute is just under 64k.
If you really need bigger attributes (that's not what the broker is meant for), we might have to rethink the attribute max size decision here at the FIWARE Foundation.
